### ISSUE TITLE
Make it a stand alone plugin you can load within a block.

### ISSUE THREAD

**Issue by Medda86** [matthiasmullie/minify#101]
Right now, you most likely only use this in the dev, but in production you still have to add the "use class" to make it work.

Example:

if ($in_dev){
use class;
}
else{
// call minifed files from dev made for production/live
}

that doesnt work as you can not call that class in a block.
Can this be rewritten? I know you only initiate a classname,
but can this be made in any way inside a block?

I also would prefer fewer includes, right now you need like 5 require_once calls.
require_once __DIR__.'/plugins/minify/src/Minify.php';
require_once __DIR__.'/plugins/minify/src/CSS.php';
require_once __DIR__.'/plugins/minify/src/JS.php';
require_once __DIR__.'/plugins/minify/src/Exception.php';
require_once __DIR__.'/plugins/minify/path-converter/src/Converter.php';

Open for discussion :)

**Comment by matthiasmullie** [comment]
I suggest you use composer to include this (and other dependencies) in your project.
Then just include the autoloader and you won't have to require all those files.

As for the `use`s, you don't have to `use` them, you can just call them by their fully qualified class name. E.g.:
```php
$minifier = new \MatthiasMullie\Minify\CSS($sourcePath);
```
