### ISSUE TITLE
Issues with JS - Removal of empty objects/function

### ISSUE THREAD

**Issue by rkorebrits** [matthiasmullie/minify#102]
I have implemented the code, but e.g. `var pb = {};` is removed from the code, likewise with `pb.Initialize = function(settings) {};`

It makes sense to remove unused code (if possible), however for us it is breaking functionality. 

Also `//` comments are retained. `/**/` Does seem to work fine. If you retain `//`, it's obviously going to break.

**Comment by matthiasmullie** [comment]
Are you sure you're using the JS minifier? `Minify\JS` doesn't remove code like that, but `Minify\CSS` does remove empty blocks (e.g. `div {}` would be removed)
The comments issue also looks like you're using `Minify\CSS` instead of `Minify\JS`, because in CSS `//` doesn't exist.
