### ISSUE TITLE
mini css file bug

### ISSUE THREAD

**Issue by bingochen87** [matthiasmullie/minify#103]
I found one when use minify to merge css file together.
If css code use some thing like "//"，minify will throw away the code after that, like: "background:url(http://example.com/test.png". minify will just merge "background:url(http:".

**Comment by matthiasmullie** [comment]
Are you sure you're using the CSS minifier?
`Minify\CSS` won't touch `//`, but `Minify/JS` will (because in JavaScript, those are comments)
