### ISSUE TITLE
Incorrect compilation of media queries with ratio

### ISSUE THREAD

**Issue by pmioni** [matthiasmullie/minify#104]
When using a media query like the following:
@media screen and (min-aspect-ratio: 16/9) { ... }
The "16/9" gets executed as if it were an operation, and you get something like 1.7777778 in the compile code. Media queries based on ratio do not accept floats, so the media query does not work.
I found a workaround:
@media screen and (unquote("min-aspect-ratio: 16 / 9")) { ... }
which compiles correctly, but it would be better if the library worked as the normal SASS compiler in these cases.

**Comment by matthiasmullie** [comment]
Are you sure this is caused by this minifier?
This minifier doesn't even attempt to execute such calculations (and I can't think of any code that would cause this artifact). I also can't reproduce it.
