### ISSUE TITLE
[CSS] Problems with "&" in import rule

### ISSUE THREAD

**Issue by Scriptman** [matthiasmullie/minify#107]
When using a "&" in the css import rule, the css becomes invalid.

Ex:
`@import "https://font.googleapis.com/css?family=RobotoDraft:regular&lang=en";`
OR:
`@import "https://font.googleapis.com/css?family=RobotoDraft:regular&amp;lang=en";`

It becomes:
`@import "https://font.googleapis.com/css?family=RobotoDraft:regular&amp;.divStyle{.....`

**Comment by matthiasmullie** [comment]
Hey @Scriptman,

I am unable to reproduce this (see 10b843d564786dbd235e6585bfdf317a9e29755c) and can't think of any code that would cause this.

Are you sure this is caused by this minifier?
Any chance you could post the complete CSS here, to help me reproduce this?

**Comment by Scriptman** [comment]
Hello @matthiasmullie,

Thank you for your reply. I can't the css code anymore what caused the issue.

My php code: 
`private function _parseCSSfile ( )
{
    require_once SYS_DIR_VENDORS . 'Matthiasmullie/PathConverter.php';
    require_once SYS_DIR_VENDORS . 'Matthiasmullie/Exceptions/BasicException.php';
    require_once SYS_DIR_VENDORS . 'Matthiasmullie/Exceptions/IOException.php';
    require_once SYS_DIR_VENDORS . 'Matthiasmullie/Exceptions/FileImportException.php';
    require_once SYS_DIR_VENDORS . 'Matthiasmullie/Exception.php';
    require_once SYS_DIR_VENDORS . 'Matthiasmullie/Minify.php';
    require_once SYS_DIR_VENDORS . 'Matthiasmullie/CSS.php';

    use MatthiasMullie\Minify;

    $oMinifier = new Minify\CSS ( );

    foreach ( $this->m_aFiles as $sFile )
    {
        $oMinifier->add ( $sFile );
    }

    return $oMinifier->minify ( );
}`

$this->m_aFiles contains an array list of css filenames to minify.

The files only contain css classes and some of them have @import "..."; at the top, nothing special.
Also, i noticed the PathConverter isn't working for me. To solve it, i use full paths now.

CSS is in: /assets/css/
Minified CSS is in: /assets/cache/
First i used: background-image: url('images/bg1.png'); url didnt change after minifying
Now i use: background-image: url('/assets/css/images/bg1.png'); which works fine.

The code above with the background-image is just an example, but it doens't reclace the url.

**Comment by matthiasmullie** [comment]
Can't investigate any further without a concrete test case, and this seems to be about multiple things (an `&`, and relative paths). Feel free to open a new ticket with the exact code examples if problems persist.
