### ISSUE TITLE
Minify bold and normal

### ISSUE THREAD

**Issue by Rolf-Smit** [matthiasmullie/minify#109]
It seems that currently the bold and normal font weights aren't minified. It would make a great addition if these would be replaced by their number counterpart (700, 400).

**Comment by Rolf-Smit** [comment]
It would also be cool if color codes like #c0c0c0 would be replaced by 'silver'.

**Comment by matthiasmullie** [comment]
Great ideas! I've done both of them!

**Comment by Rolf-Smit** [comment]
Great, I will update one of my projects soon!

**Comment by uok** [comment]
@matthiasmullie found a few more if you are interested: https://github.com/chrisnager/short-color-names
