### ISSUE TITLE
Problems with Minify, Inline JS-Code, open_basedir()

### ISSUE THREAD

**Issue by mwitzmann** [matthiasmullie/minify#111]
There is a problem using an open_basedir(), inline JS-Code and Minify (newest release).

This causes a PHP-Warning:
`Warning: is_file(): open_basedir restriction in effect. File( window.addEvent("domready", function(){ new Picker.Date( $$("#ctrl_inputCreateFromDate"),{ draggable: false, toggle: $$("#toggle_inputCreateFromDate"), format: "%d.%m.%Y", pickerClass: "datepicker_bootstrap", useFadeInOut: !Browser.ie, startDay: 1, titleFormat: "%d. %B %Y" } ); } ); ) is not within the allowed path(s): (/path/to/root/dir:/tmp:/.composer) in vendor/matthiasmullie/minify/src/Minify.php on line 385`

**Comment by fritzmg** [comment]
It appears release `1.3.28` does not have this problem.

**Comment by leofeyer** [comment]
You should probably use `@is_file()` [here](https://github.com/matthiasmullie/minify/blob/master/src/Minify.php#L385), since the argument can be the file path or the script content and the latter will cause issues with `open_basedir`.

**Comment by leofeyer** [comment]
Thank you Matthias.
