### ISSUE TITLE
Custom from and to path converter while minifying CSS

### ISSUE THREAD

**Issue by agus-prawoto** [matthiasmullie/minify#114]
Hi, is it possible to manually define the FROM and TO path converter while minifying CSS, I have read the guide (README.md file) that it automatically convert the path. I have some issue with it as the resulted path is not what i want.

The guide:
$minifier->minify('/target/path.js');

Thank you

**Comment by simonmilz** [comment]
+1

**Comment by matthiasmullie** [comment]
Hey, can you add some more detail about what exactly is wrong?

The converter makes sure that relative paths in your CSS files are adjusted if:
* the location you save the minified file is different than the original location
* `@import` file contents (inside subfolders) are imported into the main CSS body

From the current explanation, I can't really see the problem. Do you have a concrete example where this behaviour is incorrect? (please include source & target path & the original & minified code)

**Comment by agus-prawoto** [comment]
Hi your converter just works well.

I'm in situation combining multiple files from different directories and then write it in a specific folder, later, I realized that the from path was mixed so the resulted path was broken.

Maybe it useful to add a feature that we can define the from and to path manually

**Comment by matthiasmullie** [comment]
Up until now, I still have not seen a specific example where the path conversion behaves incorrectly (feature-wise, beyond what can be bugfixed)

Until I'm able to replicate problems or understand specific issues with it, I'm not keen to add a public method for disabling it.

However, I just submitted a commit that will make it a lot easier to override the path converter.
You can now subclass the minifier & make it work with a different converter, like this:

```php
class NoConverterCSS extends MatthiasMullie\Minify\CSS
{
    protected function getPathConverter($source, $target)
    {
        return new MatthiasMullie\PathConverter\NoConverter();
    }
}
```

A lot more maintainable than having to edit files in this vendor :)
