### ISSUE TITLE
Minify Bug - Regex Not Minfiied!

### ISSUE THREAD

**Issue by NizarBlond** [matthiasmullie/minify#115]
Hi,

Minifying this file ace.js https://dl.dropboxusercontent.com/u/16465802/bb-plugin/js/ace/ace.js breaks the code.

Looking at column no. 135770

`if(typeof i[s].token=="string")/keyword|support|storage/.test(i[s].token)`

Becomes 

![image](https://cloud.githubusercontent.com/assets/2389428/15653132/a25af4aa-2650-11e6-8075-d3e4103c2d7b.png)

`(typeof i[s].token=="string")/keyw.test(i[s].token)`

Cheers

**Comment by mobisync** [comment]
same problem +1
