### ISSUE TITLE
JavaScript single line comment bug

### ISSUE THREAD

**Issue by cetver** [matthiasmullie/minify#117]
After compression this file http://pastebin.com/raw/aH3jnwdz in output enters single line comments. 
Version 1.3.35

**Comment by matthiasmullie** [comment]
Hey @cetver 

I tried minifying this file myself and it seems to have worked correctly.

Can you try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.
