### ISSUE TITLE
Embed @font-face

### ISSUE THREAD

**Issue by michelollivier** [matthiasmullie/minify#119]
Hello,

Thanks for your job.

How can I setup  CSS minifier to embed following fonts ?

```
@font-face {
  font-family: 'lg';
  src: url("../fonts/lg.eot?n1z373");
  src: url("../fonts/lg.eot?#iefixn1z373") format("embedded-opentype"), url("../fonts/lg.woff?n1z373") format("woff"), url("../fonts/lg.ttf?n1z373") format("truetype"), url("../fonts/lg.svg?n1z373#lg") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

Regards
Michel

**Comment by matthiasmullie** [comment]
You can do so by setting [the extensions of files to be imported](https://github.com/matthiasmullie/minify#setimportextensionsextensions-css-only), and making sure the [max import file size](https://github.com/matthiasmullie/minify#setmaximportsizesize-css-only) is higher than the file size of the font files

Example:

```php
$minifier->setMaxImportSize(100);
$minifier->setImportExtensions(array(
	'woff' => 'application/font-woff',
	'ttf' => 'application/font-ttf',
	'eot' => 'application/vnd.ms-fontobject',
	'otf' => 'application/font-otf',
	'svg' => 'image/svg+xml',
));
```
