### ISSUE TITLE
removing a closing curly braces from a function

### ISSUE THREAD

**Issue by alexcorvi** [matthiasmullie/minify#120]
When using this library to minify a JS library called croppie ([code](http://pastebin.com/raw/qZ4NiCpC)), the function _initializeZoom loses it's closing curly bracket and causing error.

This also happened when using the [online](http://www.minifier.org/) minifier.

**Comment by alexcorvi** [comment]
I temporarily solved my issue by just including the minified JS file instead of the full one. but it's definitely a bug.

**Comment by alexcorvi** [comment]
I have just looked more deeply into this issue.
It seems like the problem is caused by this function ([link](http://pastebin.com/raw/PzQGcmJF)) having one line comments, that are not being removed.

**Those comments are not being removed because they are in the same line with a forward slash in the code.**

For example, This code:

````javascript
function myFuncName() {
    function otherFuncName() {
        if (condition) {
            a = b / 1; // comment 1
        } else if (condition) {
            a = c / 2; // comment 2
        } else if (condition) {
            a = d / 3; // comment 3
        } else {
            a = 0;
        }
    }
};
````

*results in:*
````javascript
function myFuncName(){function otherFuncName(){if(condition){a=b/ 1; //comment 1}else if(condition){a=c/ 2; //comment 2}else if(condition){a=d/ 3; //comment 3}else{a=0}}}
````

As you can see above, when minified, the code will be in one line, AND keeping all three comments; making all code that is after the first comment commented-out.

However, in this code:
````javascript
function myFuncName() {
    function otherFuncName() {
        if (condition) {
            a = b + 1; //comment
        } else if (condition) {
            a = c + 2; //comment
        } else if (condition) {
            a = d + 3; //comment
        } else {
            a = 0;
        }
    }
};
````

The comments will be removed (as they should be) and the code will be in one line.

**Comment by alexcorvi** [comment]
The extractRegex() method having this pattern `\/.*?(?<!\\\\)(\\\\\\\\)*+\/[gimy]*` is involved in this issue.

**Comment by alexcorvi** [comment]
replacing, the 

`\/.*?(?<!\\\\)(\\\\\\\\)*+\/[gimy]*` 

in the `extractRegex()` method with 

`\/.*?(?<!\\\\)(\\\\\\\\)*+\/[gimy]*(?! )(?!\/)(?![a-f])(?![hz])(?![j-l])(?![n-x])`

solves the issue, However, more tests should be done to make sure that it doesn't break other code

**Comment by matthiasmullie** [comment]
PR merged, thanks!
