### ISSUE TITLE
Error when minifying chartjs. SyntaxError: illegal character

### ISSUE THREAD

**Issue by nitinsbuzz** [matthiasmullie/minify#122]
I get the following error when trying to minify Chart js files (including bundle, minified and normal) using the following package "matthiasmullie/minify" : "1.3.34" with PHP.

I submitted an issue with chartjs/Chart.js repository but the developer of Chart.js believes the error is in the minifier.

SyntaxError: illegal character

According to firefox bug, the error is on the following line:

return value===undefined?jQuery.css(elem,type,extra):jQuery.style(elem,type,value,extra)},type,chainable?margin:undefined,chainable,null)}})});window.jQuery=window.$=jQuery;if(typeof define==="function"&&define.amd&&define.amd.jQuery){define("jquery",[],function(){return jQuery})}})(window);(function(t){"function"==typeof

**Comment by alexcorvi** [comment]
I've submitted almost the same issue here #120 
And I've solved it in this PR #121

**Comment by matthiasmullie** [comment]
That patch has been merged, thanks guys!
