### ISSUE TITLE
minify creating js errors

### ISSUE THREAD

**Issue by orizzle** [matthiasmullie/minify#130]
here is the original code: http://www.hdrrocks.com/minify.php?q=js

**Comment by PeeHaa** [comment]
Please also share the error(s).

**Comment by donini** [comment]
Hi orizzle, did you resolved this issue?

For me is occurring similar problema I gess.

When the minifier, put a code os js file bellow another in minified file, it is showing some path of my disc.

Anyone know what happens?

**Comment by orizzle** [comment]
no this issue was not resolved. i am currently looking into finding another minifier.
