### ISSUE TITLE
Minification breaks JS code.

### ISSUE THREAD

**Issue by diolemo** [matthiasmullie/minify#135]
After minification of the attached JS file the browser throws this error message:

> SyntaxError: nothing to repeat

Steps to reproduce:

1. Download/copy attached file. 
2. Paste into the [minifier.org](http://www.minifier.org) website and minify. 
3. Insert minifed JS between `<script>` tags, save and load in a browser. 

**Expected result**: no errors in console.
**Actual result**: `SyntaxError: nothing to repeat`

[marked.js.txt](https://github.com/matthiasmullie/minify/files/440935/marked.js.txt)

**Comment by matthiasmullie** [comment]
Hey @diolemo 
I just tried, but couldn't reproduce this issue.
I've just fixed a few of other issues over the last couple of hours, though, so that probably also fixed this one. Can you try again with the current minify master version?
