### ISSUE TITLE
Wrong encoding when GZIP

### ISSUE THREAD

**Issue by suncho26** [matthiasmullie/minify#140]
Hello, I have a problem when use "gzip" function.

I don't know where is the problem and would be grateful if anyone advise me on how to fix it. With the "minify" function there is no problem.

I attach picture and the CSS file.

![857494](https://cloud.githubusercontent.com/assets/3003037/19474797/e5b1214a-9539-11e6-9ec8-e5d65ffd7866.jpg)

**Comment by matthiasmullie** [comment]
I assume you're simply outputting the gzip content as-is?
You should correctly set the headers to let the receiving browser know that the content is being served as gzip:
```header("Content-Encoding: gzip");```
Also don't forget to check if the browser accepts gzip.
