### ISSUE TITLE
`(intermediate value)(...) is not a function(…)`

### ISSUE THREAD

**Issue by vanderlee** [matthiasmullie/minify#141]
I get `(intermediate value)(...) is not a function(…)` in several of my compressed javascript files.
There doesn't seem to be any good reason for this that I can see.
I've identified at least two open source projects that produce these errors:
https://github.com/zeroclipboard/zeroclipboard
https://github.com/vanderlee/interpolate

**Comment by matthiasmullie** [comment]
I tried minifying vanderlee/interpolate myself (with current master) and didn't get any syntax errors when running the code. I suggest you try minifying the code again with the current master.
If it still doesn't work then, try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.

**Comment by vanderlee** [comment]
I think this might have been a side effect of the other issue I submitted (https://github.com/matthiasmullie/minify/issues/142), as this problem seems to be gone now.
