### ISSUE TITLE
Problem with `//` comments in javascript

### ISSUE THREAD

**Issue by vanderlee** [matthiasmullie/minify#142]
Minify seems to have problems with `//` comments at the end of code lines.

The following fragment:`

```
return {
    l: ((116 * y) - 16) / 100,  // [0,100]
    a: ((500 * (x - y)) + 128) / 255,   // [-128,127]
    b: ((200 * (y - z)) + 128) / 255    // [-128,127]
};
```

Produces the following output:

```
return{l:((116*y)-16)/ 100, // [0,100]
a:((500*(x-y))+128)/ 255,   // [-128,127]
b:((200*(y-z))+128)/ 255    // [-128,127]}},_lab_to_xyz=function(lab){
```

From line ~1924 in file `jquery.colorpicker.js` of project https://github.com/vanderlee/colorpicker

I've noticed the same problem in other javascript files too.

**Comment by matthiasmullie** [comment]
Thanks for the bug report! Should be fixed in master now, and I'll try to push a new release today.

**Comment by vanderlee** [comment]
The problem is fixed. Thanks for the quick response!
