### ISSUE TITLE
I really get a 'page is not available' in Chrome, after waiting some seconds

### ISSUE THREAD

**Issue by muyncky** [matthiasmullie/minify#144]
Hello,

I use version 1.3.39 with path-converter 1.0.8. I downloaded it with composer as recommended.

Here's the hard part, I get no errors at all, not even in the php error log. For the first time in my life I started looking into the apache log (which doesn't give me any clues), but here goes nothing:
```
[Mon Nov 07 23:45:15.940477 2016] [mpm_winnt:notice] [pid 7764:tid 440] AH00428: Parent: child process 10224 exited with status 3221225477 -- Restarting.
[Mon Nov 07 23:45:16.160645 2016] [mpm_winnt:notice] [pid 7764:tid 440] AH00455: Apache/2.4.7 (Win32) OpenSSL/0.9.8y PHP/5.4.25 configured -- resuming normal operations
[Mon Nov 07 23:45:16.160645 2016] [mpm_winnt:notice] [pid 7764:tid 440] AH00456: Apache Lounge VC10 Server built: Nov 26 2013 16:07:35
[Mon Nov 07 23:45:16.160645 2016] [core:notice] [pid 7764:tid 440] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Nov 07 23:45:16.161634 2016] [mpm_winnt:notice] [pid 7764:tid 440] AH00418: Parent: Created child process 6212
[Mon Nov 07 23:45:16.738053 2016] [mpm_winnt:notice] [pid 6212:tid 436] AH00354: Child: Starting 150 worker threads.
```

Here is how I want to try the basic implementation:

```
$sourcePath = $_SERVER['DOCUMENT_ROOT'] . SUB_DIR . '/vendor/twbs/bootstrap/dist/css/bootstrap.min.css';
$minifier = new Minify\CSS($sourcePath);
// we can even add another file, they'll then be
// joined in 1 output file

$sourcePath2 = $_SERVER['DOCUMENT_ROOT'] . SUB_DIR . '/views/themes/default/css/global.css';
$minifier->add($sourcePath2);

// or we can just add plain CSS
$css = 'body { color: #000000; }';
$minifier->add($css);

// save minified file to disk
$minifiedPath = $_SERVER['DOCUMENT_ROOT'] . SUB_DIR . '/cache/css/'. $controllerName .'.min.css';
$minifier->minify($minifiedPath);

// or just output the content
echo $minifier->minify();

```

The path should be fine too, I printed the first one: `C:/xampp/htdocs/bluerasp/vendor/twbs/bootstrap/dist/css/bootstrap.min.css`

Any suggestion would be much appreciated.

**Comment by matthiasmullie** [comment]
What exactly is wrong? Does it not generate the minified file, is there an error in the minified files, ...?

**Comment by muyncky** [comment]
It doesn't generate the minified file. The only error I can see now in the php error log is:
`[11-Nov-2016 13:43:33 Europe/Berlin] PHP Warning:  preg_replace_callback(): Requires argument 2, '', to be a valid callback in C:\xampp\htdocs\bluerasp\vendor\matthiasmullie\minify\src\CSS.php on line 542
`
But I only get this once, not every time I reload, so I don't know if this is related. This is also why I didn't include it in the first place. I see it for the second time now.

**Comment by matthiasmullie** [comment]
What PHP build/version are you using? Has the source code been changed in any way?

That error is really odd: that 2nd argument can only be the closure from L538-540 and is a valid callback. Unless that source file has been tampered with somehow, I can not think of anything that would cause this.
PHP>=5.3 versions should all properly process this. Older PHP versions should fail with a parse error. I tested & confirmed this on 3v4l.org. I have no idea here :p

**Comment by muyncky** [comment]
Good you mentioned the environment. I got it working on my hosting (linux). But localhost with XAMPP and PHP 5.4 still doesn't work.
Some more details:
XAMPP Control Panel v3.2.1
Windows 8.1

I made some changes in php.ini, like higher upload size en increase max input vars. I configured vhost file to accept more hostnames. I don't know if that has any effect on the matter.
I see that XAMPP "v5.6.24 (PHP 5.6.24)" is available, I might try to update it.

Thanks for the replies. I will try to locate the problem on my environment. I will post something if I find anything.

**Comment by muyncky** [comment]
The problem doesn't occur anymore after updating XAMPP from v3.2.1 to v3.2.2. It wasn't updated for 2 years I guess. The previous install had some things configured, like:
- php.ini: increasing `stuff`
- httpd-vhosts.conf: adding hostnames/ports
- httpd.conf opening ports

So I don't know what it was, but it is 'solved'.

**Comment by matthiasmullie** [comment]
Alright, glad it was an environment issue, and that it has been fixed now :)
