### ISSUE TITLE
Critical bug: the CSS::stripEmptyTags can accidentally strip out all @import statements

### ISSUE THREAD

**Issue by nguyenvuduc** [matthiasmullie/minify#145]
Assume that we have a css like this:
```
    /* some imports */
    @import ('./css1.css'); 
    @import url('https://www.google.com/main.css')

    .empty-rule{
    }

    body{
         background; white;
    }
```

The minify will return:
```
    body{
         background; white;
    }
```

It strips out everything from .empty-rule{} up to beginning of the file. The cause of the bug is in CSS:stripEmptyTags. Its regular expression doesn't cover the case of empty tag at the top of the page.
```
    protected function stripEmptyTags($content)
    {
         return preg_replace('/(^|\})[^\{\}]+\{\s*\}/', '\\1', $content);
    }
```

**Comment by matthiasmullie** [comment]
Thanks for the bug report! Should be fixed in master now, and I'll try to push a new release today.

**Comment by nguyenvuduc** [comment]
Thank you very much.
