### ISSUE TITLE
SyntaxError: unterminated parenthetical

### ISSUE THREAD

**Issue by jbelien** [matthiasmullie/minify#146]
Hi,

I just updated to `1.3.40` and I have an error I didn't have with version `1.3.39`.

When I try to minify `jQuery 3.1.0` and `bootstrap 3.3.7` in a single file, and try to load the resulting file in my page, I have the following JavaScript error  :

    SyntaxError: unterminated parenthetical [1:72483]

Thanks.

**EDIT:** I switched back to `1.3.39` and I do not have the error. I confirm the error is in version `1.3.40`.

**Comment by matthiasmullie** [comment]
What are the exact files you used?
I tried with https://code.jquery.com/jquery-3.1.0.js & https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.js and I don't get the syntax error when loading the combined minified result.

**Comment by jbelien** [comment]
I used these to files (had to rename it in `.txt` to upload it here) :
[jquery-3.1.0.min.txt](https://github.com/matthiasmullie/minify/files/583481/jquery-3.1.0.min.txt)
[bootstrap.min.txt](https://github.com/matthiasmullie/minify/files/583479/bootstrap.min.txt)
It generated following file :
[base.txt](https://github.com/matthiasmullie/minify/files/583480/base.txt)

I tried to minify uncompressed files :
[jquery-3.1.0.txt](https://github.com/matthiasmullie/minify/files/583491/jquery-3.1.0.txt)
[bootstrap.txt](https://github.com/matthiasmullie/minify/files/583490/bootstrap.txt)
and had the following error :

    SyntaxError: unterminated regular expression literal


I use the following code to compress them :

    $js_required = new Minify\JS();
    $js_required->add('jquery-3.1.0min.js');
    $js_required->add('bootstrap.min.js');
    $js_required->minify('base.js');

**Comment by matthiasmullie** [comment]
I just tried with the files you provided.
With the first 2 (already minified), I got the exact same result as your base.txt.
Loading that one, I don't get any syntax errors.

With the 2 not yet minified files, this was the result:
[combined.txt](https://github.com/matthiasmullie/minify/files/583631/combined.txt)
When I load that, I still don't get any syntax errors.

Any chance you can copy the minified result that you get (to compare against mine)?

**Comment by jbelien** [comment]
Here is the resulting minified file from uncompressed jQuery and Bootstrap :
[base-uncompressed.txt](https://github.com/matthiasmullie/minify/files/583647/base-uncompressed.txt)

Thanks for your help.

**Comment by jbelien** [comment]
Just for information, I use Firefox 49.0.2

**Comment by solverat** [comment]
we also experience some problems with the js regex. when i change back that line from 1.3.39, everything works fine:

https://github.com/matthiasmullie/minify/commit/7dd8d25fdbe2535c5b8d73058283e388933dd7ea#diff-e837fffca2f31746095c8e1651effe75R230

**Comment by matthiasmullie** [comment]
@jbelien AFAICT, base-uncompressed.txt is the result of minifying the already-minified versions of bootstrap & jquery (you can tell because the variable names have been changed already, which is not something this minifier does). And if I load base-uncompressed.txt, I don't get the syntax error.
Any chance you posted the wrong file?

@solverat any chance you can copy/link to some example that now fails to minify correctly?

**Comment by jbelien** [comment]
@matthiasmullie : You're totally right, I did post the wrong file... So sorry !

Here is the good one : [base-uncompressed.txt](https://github.com/matthiasmullie/minify/files/583691/base-uncompressed.txt)

Error (line 481) : 

    SyntaxError: unterminated regular expression literal [481:876]

**Comment by solverat** [comment]
file: `jquery-1.12.0.min.js`
position: `Kb=/^(?:GET|HEAD)$/,`

**Comment by matthiasmullie** [comment]
Both of your problems are in the exact same spot of jquery's code.

Odd and annoying that it's working fine for me, though - means I can't reproduce and test any fix.
I just pushed a potential fix - can any of you try minifying jquery with this fix and confirm whether or not it works?

**Comment by jbelien** [comment]
Nice 👍 

I try this now !

**Comment by matthiasmullie** [comment]
What version of PHP are you using?
And what are the values for pcre config on your setup?
```php
echo ini_get( 'pcre.backtrack_limit' ), ',', ini_get( 'pcre.recursion_limit' ), ',', ini_get( 'pcre.jit' );
```

I'll try to set up an environment as similar to yours as possible.

**Comment by jbelien** [comment]
PHP 7.0.12-1~dotdeb+8.1

    pcre.backtrack_limit = 1000000
    pcre.recursion_limit = 100000
    pcre.jit = 1

**Comment by matthiasmullie** [comment]
Alright, thanks. I'll try to set up something similar in the next couple of days.
Meanwhile, any chance you could try again with current master? I just pushed another change to the regex extraction.

**Comment by jbelien** [comment]
I'll try it first time tomorrow morning !
Thanks for your help.

**Comment by jbelien** [comment]
No sorry, still the same error ...

**Comment by matthiasmullie** [comment]
Under PHP7, I was also seeing some unexpected results.
I've restored the previous regex detection method, since the reason I had changed it no longer applies (fixed elsewhere). I'm pretty sure this should fix the problem on your end, since this is exactly what used to work before.
Just reopen this issue if it wasn't fixed after all!

**Comment by jbelien** [comment]
Thanks for all the work ! :)
I'll check this tomorrow or the day after !

**Comment by jbelien** [comment]
Problem fixed 👍 
Good job ! Keep on the good work !

**Comment by Libcurl-abused** [comment]
@matthiasmullie https://jqcode.space/questions/is-there-a-way-to-generate-a-txt-document-utilizing-jquery
