### ISSUE TITLE
Bugs when convert Beaver Builder js files

### ISSUE THREAD

**Issue by hamdallah90** [matthiasmullie/minify#148]
Hello,

After I have minified the Beaver builder js files, I got a Javascript syntax error,

you can download the files from here:
Before : https://ufile.io/9b422

After: https://ufile.io/ae026

Thanks

**Comment by matthiasmullie** [comment]
Hey @hamdallah90 

I tried minifying this file and it seems to have worked just fine, without syntax errors.
Can you try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.
Also make sure you're using the latest tag (currently 1.3.41).

If the problem persists, feel free to reopen this ticket with some additional details (PHP version, pcre config, ...)

**Comment by hamdallah90** [comment]
thanks its working :)
