### ISSUE TITLE
This bit of CSS is breaking it

### ISSUE THREAD

**Issue by adi518** [matthiasmullie/minify#149]
.headerWrapper{
        /*background:url(/_media/images/general/bg_top_right.png) no-repeat;*/
        background:url('') no-repeat;
        background-position:100% 0;
        width:100%;
        min-height: 0;
    }

Result is broken because of the empty string in line 2. It seems the problem might stem from a combination of the comment above it. If I comment line 2, it fixes it, but merely a workaround.

The break itself results in shoving properties from following object declarations into the value of the background property:

`background: url(') no-repeat;background-position:100% 0;width:100%;min-height:0}.headerRightBg{background:url(/_media/images/general/bg_top_right.png) no-repeat;background-position:100% 0;width:221px;height:154px;position:absolute;right:0;top:0}.headerLeftBg{background:url(/_media/images/general/bg_left.png) no-repeat;background-position:0 0;width:315px;height:500px;position:absolute;left:0;top:0}.headerWrapper:before{content:"";height:4px;width:100%;display:inline-block;background-color:#f7931d;position:absolute;z-index:1}#header{position:relative}.nav{height:35px;line-height:35px;padding-top:5px;margin:0;padding:0;width:762px;display:inline-block;border-bottom:1px solid #d4d4d4;margin-top:5px;overflow:hidden}.nav li{display:inline-block;list-style:none;vertical-align:top;white-space:nowrap}.nav li a{font-size:14px;color:#484c49;display:inline-block;line-height:35px;height:35px;padding:0 8px 0 8px}.nav .personIcon{background-position:-200px -27px;width:18px;height:21px;position:relative;top:4px}.nav .myZone a{color:#046994}#header>ul>li.myZone{display:inline-block;width:138px;white-space:nowrap}.logoWrapper{display:inline-block;float:left;margin:22px 0 0 0;position:relative;z-index:1;margin-right:34px;position:absolute}.logo{background-position:0 0;width:160px;height:81px}.homepageIcon{background-position:-200px 0;width:21px;height:17px;position:relative;top:4px}#footerWrapper{background:#4c5255;border-top:1px solid #42474b}#footer{color:#fff;margin-bottom:18px}#footer a{color:#fff}#footer .block{width:223px;display:inline-block;vertical-align:top;padding-top:16px}#footer .block ul{border-left:1px solid #42474b;width:204px}#footer .block .social{border-left:0}#footer .block p{font-size:12px;color:#fff;width:138px}.block ul li{list-style:none;vertical-align:top}#footer .block ul .gIcon{background-position:0 -98px;width:37px;height:37px}#footer .block ul .twitterIcon{background-position:-158px -98px;width:37px;height:37px}#footer .block ul .ytIcon{background-position:-104px -98px;width:37px;height:37px}#footer .block ul .fbIcon{background-position:-52px -98px;width:37px;height:37px}#footer .block ul .fbIcon{background-position:-52px -100px;width:37px;height:37px}#footer .block ul.social{margin-top:0;text-align:left}#footer .block ul.social li{display:inline-block;margin:0 10px 0 0}.copyrights a{color:#fff}.copyrights{border:1px solid #42474b;text-align:center;color:#fff}.copyrights p{display:inline-block;height:35px;line-height:35px;margin:0;color:#fff}#breadcrumb{list-style-type:none;font-size:0}#breadcrumb li{display:inline-block;font-size:14px}.checked{background-image:url('/_media/images/form/checkbox_select.png)`

**Comment by matthiasmullie** [comment]
Hey @adi518 

I tried minifying this file and it seems to have worked just fine (see commit c0582c845116c8bbad4d8a1be6234ba5297f88fa).
Can you try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.
Also make sure you're using the latest tag (currently 1.3.42).

If the problem persists, feel free to reopen this ticket with some additional details (complete CSS, PHP version, pcre config, ...)

**Comment by adi518** [comment]
Sweet. Will update soon.
