### ISSUE TITLE
[CSS] Negative numbers problem

### ISSUE THREAD

**Issue by UnBichitoVerde** [matthiasmullie/minify#150]
Hi! I've noticed that there's a problem with negative numbers, I've seen there is a closed issue related to this but is still breaking css.

The input:
`.text {
	box-shadow: 0 0 1em -0.5em #000;
}`

The result:
`.text{box-shadow:0 0 1em-0.5em #000}`

Could you please review it? Thank you!

**Comment by matthiasmullie** [comment]
Hey @UnBichitoVerde 

I tried this, but couldn't reproduce the issue.
Any chance you are using an older Minify version? Can you try again with the latest release (1.3.42 atm)?
Feel free to reopen should you still experience the issue with the latest release!
