### ISSUE TITLE
Class IOException not found

### ISSUE THREAD

**Issue by sbulen** [matthiasmullie/minify#154]
I got the following (this text is from my apache log):

> PHP Fatal error: Class 'MatthiasMullie\Minify\Exceptions\IOException' not found in (path)\Sources\minify\src\Minify.php on line 400

No I/O error in my Windows event log. Nonetheless, it appears an exception was thrown somewhere & there was nothing there to catch it...

Is there something users should do to utilize these classes & fold Minify into their application's error processing?

**Comment by matthiasmullie** [comment]
It looks like you were not including the exception classes:

```php
require_once $path . '/minify/src/Exceptions/BasicException.php';
require_once $path . '/minify/src/Exceptions/FileImportException.php';
require_once $path . '/minify/src/Exceptions/IOException.php';
```

I've updated https://github.com/matthiasmullie/minify/issues/83 to reflect that these should also be included.
