### ISSUE TITLE
Minifing of jQuery does not work

### ISSUE THREAD

**Issue by phoebusryan** [matthiasmullie/minify#157]
I wanna minify a bunch of assets and the minifier breaks when jQuery (1.3.X) is in the set.

The problem is this code (jquery.1.3.3.js line 8473 - 8475):
```
rlocalProtocol = /^(?:about|app|app-storage|.+-extension|file|res|widget):$/,
rnoContent = /^(?:GET|HEAD)$/,
rprotocol = /^\/\//,
```

minfied version:
```rlocalProtocol=/^(?:about|app|app-storage|.+-extension|file|res|widget):$/,rnoContent=/^(?:GET|HEAD)$/,rprotocol=/^\/\```

the problem is the missing `//,` at the end (because minfy thinks this is a comment)....

how can we fix that?

**Comment by matthiasmullie** [comment]
Where can I find that file?

http://code.jquery.com/jquery-1.3.3.js doesn't exist, and looking at https://github.com/jquery/jquery/releases?after=1.4.3rc2, there never was a 1.3.3 release.

**Comment by phoebusryan** [comment]
Hell sorry... i meant 3.1.1 ...

**Comment by zellerda** [comment]
Same problem here I have change in jquery.js at line 8475 "rprotocol = new RegExp('^\/\/'),"
This is not the solution but it can help waiting the fix.

**Comment by matthiasmullie** [comment]
I tried minifying http://code.jquery.com/jquery-3.1.1.js and it seems to have worked just fine (see commit c0582c8).
Can you try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.
Also make sure you're using the latest minifier code!

If the problem persists, feel free to reopen this ticket with some additional details (complete CSS, PHP version, pcre config, ...)

**Comment by StefanKoenen** [comment]
@matthiasmullie please have a look into this.
This is still an issue, also for https://github.com/matthiasmullie/minify/issues/173. YES the minify is working (without increasing the pcre limits), but please try to load the minified file in the browser, it will give errors. (atleast for jQuery v2.2.4)
