### ISSUE TITLE
Prevent *.min.(js|css) files to be minfied again

### ISSUE THREAD

**Issue by phoebusryan** [matthiasmullie/minify#158]
I wanna bundling custom files and vendors into one file. the problem ist, that minfied files minifing again often breaks the JS. IMO we should ignore files with the namepattern *.min.(js|css) and just bundle it.

What do you think?

**Comment by matthiasmullie** [comment]
I agree that files that have already been minified should not be minified again.
However, I don't think Minify should skip such files. It's up to whoever is using Minify to make sure that files that don't have to be minified anymore are not added to the minifier :)

Something like this should work (untested):

```php
$minify = new Minify();
$other = [];

$files = glob($source . '/*.js');
foreach ($files as $file) {
    if (strpos($file, '.min.js') === false) {
        $minify->add($file);
    } else {
        $other[] = trim(file_get_contents($file));
    }
}

$content = $minify->minify($destination);
foreach ($other as $code) {
    $content .= ';' . trim($code, ';');
}
file_put_contents($destination, $content);
```
