### ISSUE TITLE
Fatal error: Interface ConverterInterface not found

### ISSUE THREAD

**Issue by uok** [matthiasmullie/minify#160]
Hello,

After updating to minify 1.3.43 and path-converter 1.1.0  there is this error
`Fatal error: Interface 'MatthiasMullie\PathConverter\ConverterInterface' not found`
Until now everything worked perfectly by using
```
include("minify/src/Minify.php");
include("minify/src/CSS.php");
include("minify/src/Exception.php");
include("path-converter/src/Converter.php");
```
Any ideas?
Thanks and keep up the good work!

**Comment by matthiasmullie** [comment]
Yeah, now you also have to include path-converter/src/ConverterInterface.php :)

**Comment by uok** [comment]
ok, I updated the includes and it works again 🎉 
```
include("minify/src/Minify.php");
include("minify/src/CSS.php");
include("minify/src/Exception.php");
include("path-converter/src/ConverterInterface.php");
include("path-converter/src/Converter.php");
```
Thanks and keep up the good work!
