### ISSUE TITLE
Issue with single quote

### ISSUE THREAD

**Issue by wiloke** [matthiasmullie/minify#162]
Hi there,
Firstly, thanks for your great tool!
I found an issue with CSS compression  if a CSS file contains single quote, for example
`background-image:url("data:image/svg+xml;charset=utf-8,` [http://idangero.us/swiper/#.WJLpebZ95TZ](url)
will make broken compression file.
Best regards

**Comment by javiereguiluz** [comment]
I don't know if it's related, but when updating `matthiasmullie/minify (1.3.42 => 1.3.43)` one of my applications broke because `background: url('data:image/svg+xml;utf8,<svg ...>')` is transformed into `background: url(data:image/svg+xml;utf8,<svg ...>)` (the single quotes of the url() value are missing) which is incorrect.

**Comment by weimate** [comment]
Hello there,
any news on this issue? I have the same problem with an external css file.
Thanks!

**Comment by weimate** [comment]
@matthiasmullie  should we use another minifier? Or will this be fixed?

**Comment by javiereguiluz** [comment]
@weimate I can understand your urgency about this issue ... but please keep in mind that this is Open Source and @matthiasmullie is volunteering his work in this project. Let's not put more pressure on him :)

For now, you can fix this issue by locking the `minify` dependency to the previous version that didn't contain this error:

```json
"matthiasmullie/minify": "1.3.42",
```

**Comment by matthiasmullie** [comment]
Don't worry, this will be fixed, but I only have so much time :) I'll *try* to take a look today/this week.

**Comment by weimate** [comment]
Thanks! :)

**Comment by weimate** [comment]
@javiereguiluz I understand your point. It is not urgent, I just wanted a response about the future of this issue! :)

**Comment by matthiasmullie** [comment]
Just pushed a fix. Any chance anyone could confirm this actually fixes the issue?

**Comment by javiereguiluz** [comment]
I'm sorry but it doesn't fix the problem for me. The `if (preg_match(...))` condition is always `false` in my case. The URLs are like: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="389.688" height="99.122" viewBox="0 0 365.33...`

**Comment by matthiasmullie** [comment]
Another commit - does this work?

**Comment by javiereguiluz** [comment]
Yes! It worked like charm! Thank you.
