### ISSUE TITLE
Number converted to a regex

### ISSUE THREAD

**Issue by tate-u** [matthiasmullie/minify#163]
Just want to give you a heads up!
I am using Minify on a 40,000 line js file and encountered one issue, after I changed my code, it worked flawlessly..

Problem Line
q = d / 4 / b.width()

Converts to
q=h/\d+\.?\d?/b.width

I changed to the following to make it work...
q = (d / 4) / b.width()

**Comment by matthiasmullie** [comment]
I tried minifying your example and it seems to have worked just fine (see commit a7fc4a98ef8f2cf38bba701b51f1a84a1d67bc5c).
Can you try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.
Also make sure you're using the latest minifier code!

If the problem persists, feel free to reopen this ticket with some additional details (complete JS, PHP version, pcre config, ...)
