### ISSUE TITLE
JS merging strips away too much causing a broken merged JS file

### ISSUE THREAD

**Issue by mitchvdl** [matthiasmullie/minify#164]
The example code:
```
Calendar.createElement = function(type, parent) {
    var el = null;
    if (document.createElementNS) {
        // use the XHTML namespace; IE won't normally get here unless
        // _they_ "fix" the DOM2 implementation.
        el = document.createElementNS("http://www.w3.org/1999/xhtml", type);
    } else {
        el = document.createElement(type);
    }
    if (typeof parent != "undefined") {
        parent.appendChild(el);
    }
    return el;
};
```
Seems to merge into:
```
Calendar.createElement=function(type,parent){var el=null;if(document.createElementNS){el=document.createElementNS("http:}else{el=document.createElement(type)}
if(typeof parent!="undefined"){parent.appendChild(el)}
return el};
```

As you can see the double slash from http:// is stripped out causing the whole line to fail resulting in ``Uncaught SyntaxError: Invalid or unexpected token``

Escaping all the lines with ``http:\/\/`` resolves the issue but involved updating existing libraries.

**Comment by chaitanyathengdi** [comment]
It seems that the minifier thinks the content after the // in http:// is a comment.

**Comment by jlaustill** [comment]
I'm having this same issue today.  I'll attach my raw file, but the lines giving me issue are the following

`$(this).find('iframe').hide().attr('src', '//about:blank').end().empty();`

Getting minified to 

`$(this).find('iframe').hide().attr('src','}catch(e){}});`

The source is getting cut off right at the //about and wrapping to the next line, so I assume it is being treated like a comment as well.  I tried doubling the recursion_limit and backtrack_limit and got the same behavior.  

I also don't see a version number in my composer.json file, so I'll go ahead and update and see what happens, but I only installed this library a few weeks ago, so I can't be THAT far behind...

[6998f89617e4c252ce489056e898601e.min.js.zip](https://github.com/matthiasmullie/minify/files/868979/6998f89617e4c252ce489056e898601e.min.js.zip)

**Comment by matthiasmullie** [comment]
I just tried this line, and it minifies correctly for mee (see commit b431a11bc55f3dd33de8552275d13821ae8e2bdb)

I can only guess your PCRE settings are not optimal (unable to parse the whole file) and as a result fails to properly recognize all strings & sees content inside of strings as possible code (or comments, in this case). Please try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)
