### ISSUE TITLE
incorrect font urls after CSS minify

### ISSUE THREAD

**Issue by mimmi20** [matthiasmullie/minify#165]
I our project we have font urls in the css like
```css
src: url('../../font/archivo_narrow_regular.eot?#iefix') format('embedded-opentype')
```
or 
```css
url('../../font/archivo_narrow_regular.svg#archivo narrow') format('svg')
```
.

After the minify the colons are removed and the browsers don't load these fonts.

In these cases, when a url suffix is available, minify should leave the single colons.

**Comment by billynoah** [comment]
+1.  same issue here

**Comment by fernandoval** [comment]
See this issue: https://github.com/matthiasmullie/minify/issues/153

**Comment by mimmi20** [comment]
This is not the same issue. In our application the fonts are found and loaded when the paths are surrounded by colons.

**Comment by mimmi20** [comment]
Thanks
