### ISSUE TITLE
Missing Class for relative path command line usage

### ISSUE THREAD

**Issue by squivo** [matthiasmullie/minify#169]
Hi there, just trying to use `minifyjs` and `minifycss` from the command line.  I installed the git repo just fine into a user directory `/User/squivo/minifier/minify` and added the /bin folder to my $PATH. When I run the minify commands via command line I get this error: 

`PHP Fatal error:  Class 'MatthiasMullie\PathConverter\Converter' not found in /Users/squivo/minifier/minify/src/CSS.php on line 688`

Looks like this class is missing from the repo?

**Comment by matthiasmullie** [comment]
That class is part of https://github.com/matthiasmullie/path-converter

If you use composer to install minify, path-converter should also automatically be included.
If you don't use composer, you can check out these instructions: https://github.com/matthiasmullie/minify/issues/83
