### ISSUE TITLE
[Feature] Minify HTML

### ISSUE THREAD

**Issue by ulfgebhardt** [matthiasmullie/minify#170]
I'm using your Lib in my projects, but to minify HTML I have to get another lib.

I would like to have this one include HTML minify <3

Thanks for the good work!

"Helpful" Links - this is just from the top of google....
- https://gist.github.com/tovic/d7b310dea3b33e4732c0
- https://coderwall.com/p/fatjmw/compressing-html-output-with-php
- https://websistent.com/how-to-use-php-to-minify-html-output/

**Comment by matthiasmullie** [comment]
While I don't have any plans to implement this myself at this point, I'm willing to merge a good pull request & help it maintain. In #152, someone already expressed interest in developing this.
