### ISSUE TITLE
"continue" unterminated with semicolon

### ISSUE THREAD

**Issue by jameswtc** [matthiasmullie/minify#178]
Hi,
The JS minify seems fail the correctly minify the following scripts (taken from lunr.js)

```
lunr.SortedSet.prototype.add = function () {
  var i, element

  for (i = 0; i < arguments.length; i++) {
    element = arguments[i]
    if (~this.indexOf(element)) continue
    this.elements.splice(this.locationFor(element), 0, element)
  }

  this.length = this.elements.length
}
```
The resulting combined and minified JS produces the following error:

![screen shot 2017-05-28 at 21 04 39](https://cloud.githubusercontent.com/assets/9884884/26531432/4c785f20-43e9-11e7-944f-e2e934de0209.png)

This might be a bug to resolve?

Thanks!

James

**Comment by mahagr** [comment]
Looks like the same issue as the one in the issue mentioned above.

**Comment by matthiasmullie** [comment]
Thanks for the report! Fixed!

**Comment by flaviocopes** [comment]
Thanks for the quick patch & release @matthiasmullie 😃
