### ISSUE TITLE
Bug @ single-line comments

### ISSUE THREAD

**Issue by Sven-Mad** [matthiasmullie/minify#182]
in my code, i have those line:
`label = input.val().replace(/\\/g, '/').replace(/.*\//, '');`
after the minify, this line looks as follows:
`label=input.val().replace(/\\/g, '/').replace(/.*\`

i modify regex in JS.php line 190 to
`$this->registerPattern('#(?<!\\\)\/\/.*$#m', '');`

now its works

**Comment by matthiasmullie** [comment]
Thanks for the report! Fixed!
