### ISSUE TITLE
CSS also removes classname [space] *

### ISSUE THREAD

**Issue by BasSilderhuis** [matthiasmullie/minify#183]
After minify these classes become like this

.mce-container,
.mce-container *,
.mce-widget,
.mce-widget *,
.mce-reset {

.mce-container,.mce-container*,.mce-widget,.mce-widget*,.mce-reset{

It looks like chrome whon't apply this rule because of the missing space between the star and the class name.

**Comment by matthiasmullie** [comment]
I tried minifying this example and it seems to have worked just fine (see commit 3fcd6421dfc3d27a45207c07ffb57f8e4c12d3a5).
Can you try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.
Also make sure you're using the latest minifier code!

If the problem persists, feel free to reopen this ticket with some additional details (complete JS, PHP version, pcre config, ...)
