### ISSUE TITLE
Too much minification on *

### ISSUE THREAD

**Issue by peixotorms** [matthiasmullie/minify#184]
Note, this is the same as https://github.com/matthiasmullie/minify/issues/183

The problem the user reported, is not about "failed" minification... so it's not relevant to increase the pcre.backtrack_limit & pcre.recursion_limit 

What the user is saying exactly, is that:

`.mce-container *,.mce-widget`
becomes:
`.mce-container*,.mce-widget`

Which will cause the style to be ignored on several browsers.

On my specific case, I'm minifying a css file from a popular image gallery, this file:
`http://8147-presscdn-0-3.pagely.netdna-cdn.com/wp-content/plugins/soliloquy/assets/css/soliloquy.css`

What happens here, is that the file is minified and there is no error.
I can see that it was minified completely... however, like the issue on #183, what happens here is that 

`.soliloquy-container, .soliloquy-container * {`
becomes:
`.soliloquy-container,.soliloquy-container* {`

and the lack of space before `*` will cause the styling to break.

Likewise, further down:

`background: transparent url(images/preloader.gif) no-repeat scroll 50% 50%;`
becomes:
`background: transparent url(images/preloader.gif)no-repeat scroll 50%50%;`

While I haven't specifically tested this one, it also seems to break the design on the page.

Kindly preserve the space before `*` and after `)` so design won't be broken.
Thanks.

**Comment by matthiasmullie** [comment]
I tried minifying these examples as well as http://8147-presscdn-0-3.pagely.netdna-cdn.com/wp-content/plugins/soliloquy/assets/css/soliloquy.css and it seems to have worked just fine (see commit 0b3f4f7a26747f1d420882973273c3a392ade568).
Can you try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.
Also make sure you're using the latest minifier code!

If the problem persists, feel free to reopen this ticket with some additional details (complete CSS - including other scripts that may be minified all at once, PHP version, pcre config, ...)

**Comment by peixotorms** [comment]
Can you possibly tell me in which PHP version and in which operating system are you testing this?

I obviously increased the limit of pcre.backtrack_limit & pcre.recursion_limit before contacting you, and this still happens with the latest code, on Ubuntu 16.04 and PHP 7.1.

If PHP behaves differently on another OS or on another version, I can accept that.
Nevertheless, if "we" can sort this, it would be great for everyone.

I would like to test this on my end too, once I get to try using the same PHP and OS as you.

Thanks.

**Comment by matthiasmullie** [comment]
I'm on macOS 10.12.5 (OS shouldn't theoretically be relevant - php/pcre *should* behave the same), with PHP 7.1.4.
pcre.backtrack_limit is set to 1000000, pcre.recursion_limit to 100000.

Are you minifying only this 1 file, or is it combined with others? (one of the other files could influence minification of this one, even if those appear fine)

**Comment by peixotorms** [comment]
I can confirm that the css minification is working properly.

What happened here, is that a script I was using, was doing JS minification on that CSS file, instead.
Sorry for the trouble, all perfect.

**Comment by matthiasmullie** [comment]
Oh alright, no worries - glad you got it sorted out!
