### ISSUE TITLE
[JS] Wrong handling of tilde `~` operator

### ISSUE THREAD

**Issue by alvov** [matthiasmullie/minify#185]
**Version:** 1.3.45, also online minifier at http://www.minifier.org
**What did you try to do?** Minify https://github.com/getsentry/raven-js/blob/master/dist/raven.js
**What went wrong?**
The minified version contains the line:
```
~thisPos?stack.splice(thisPos+1):stack.push(this)~thisPos?keys.splice(thisPos,Infinity,key):keys.push(key)
```
which causes an `Unexpected token ~` syntax error when executed because of the `push(this)~thisPos` part.
**What was the expected result?**
The same line but with a line-break (or `,`, or `;`) before the `~` operator:
```
~thisPos?stack.splice(thisPos+1):stack.push(this)
~thisPos?keys.splice(thisPos,Infinity,key):keys.push(key)
```

My quick attempt was to exclude `~` from `data/js/operators_after.txt` file, but I'm still not sure if it would be the correct fix.

Thank you!

**Comment by matthiasmullie** [comment]
Excluding it from operators_after.txt was indeed the perfect solution :)
Thanks!

**Comment by alvov** [comment]
Thanks in return :)
