### ISSUE TITLE
moment-timezone.min.js Corrupts the Javascript minify process

### ISSUE THREAD

**Issue by kcookrunning** [matthiasmullie/minify#186]
While using this library to combine JS files I ran across an interesting bug while attempting to combine a moment-timezone.min.js JS lib with other JS.

I managed to recreate the issue with a few lines of JS that were stripped out and simplified from a moment-timezone.min.js file.

```
use MatthiasMullie\Minify;

$minifier = new Minify\JS();

$minifier->add( 'd/=60;z("/foo/.")
/*! This comment should be removed by the minify process */

var str1 = "//this-text-shoudl-remain-intact";
var str2 = "some other string here";' );

echo $minifier->minify();
```

The output of the PHP code is below. The parsing stripped code after a `//` and the `/*..*/` comment is not removed. A JS syntax error is introduced here due to the closing `"` having been removed

```
d/=60;z("/foo/.")
/*! This comment should be removed by the minify process */

var str1 = "
var str2="some other string here"
```

**Comment by kcookrunning** [comment]
The extractRegex() pattern is considering `/=60;z("/` as a regular expression.  This is then replaced with a `/$count/` which leaves the broken double quote string.

```
d/=60;z("/.")
/*! This comment should be removed by the minify process */

var str1 = "//this-text-shoudl-remain-intact";
var str2 = "some other string here";
```

Is changed to

```
d/1/.")
/*! This comment should be removed by the minify process */

var str1 = "//this-text-shoudl-remain-intact";
var str2 = "some other string here";
```

This then puts the quoted string in the wrong place and breaks the JS.

So far my fix has been to update the extractRegex() pattern so that `/=` is ignored for a regex match

old
```
$pattern = '\/.*?(?<!\\\\)(\\\\\\\\)*\/[gimy]*(?![0-9a-zA-Z\/])';
```
new
```
$pattern = '\/[^=]*?(?<!\\\\)(\\\\\\\\)*\/[gimy]*(?![0-9a-zA-Z\/])';
```

**Comment by matthiasmullie** [comment]
Hi @kcookrunning 

Thanks for the very detailed report! And your suggested fix seems fine.

Can you submit a pull request with that fix and your test case (which you can add here: https://github.com/matthiasmullie/minify/blob/master/tests/js/JSTest.php#L995)

If you're unable to submit a PR, I'll eventually do it myself, but I'm currently traveling.

Thanks!

**Comment by kcookrunning** [comment]
Hi @matthiasmullie 

I have implemented that change to my local copy and have installed this on a few sites for testing. 

I'll leave the PR and merge up to you as there is no rush on this

**Comment by matthiasmullie** [comment]
Done! Thanks again!
