### ISSUE TITLE
add package to Atom editor (apm)

### ISSUE THREAD

**Issue by Artlant** [matthiasmullie/minify#187]
I think it would be cool if you added your application as an extension to the Atom editor

**Comment by matthiasmullie** [comment]
That would be great, but I have no idea how to make an Atom extension, and am a little short on time to try to figure that out & build it :)

If you (or anyone else) wants to take this up, you have my blessing and I'll be glad to help out where I can!

**Comment by Artlant** [comment]
@matthiasmullie I sorry, but better not let me go to someone else's code - I have the gift to make it horrible ). But as far as I understand this is easy:
http://blog.fxndev.com/create-your-first-atom-package-in-js/
 And distribution for other editors is able to increase users. 

Thanks for answering, and good luck in improving your minifity-app
