### ISSUE TITLE
Removal of semi-colons is too wild

### ISSUE THREAD

**Issue by func0der** [matthiasmullie/minify#189]
https://github.com/matthiasmullie/minify/blob/1443646268465b8930c9a7f2f8ff1a51453796d1/src/JS.php#L352

This line removes too many semi-colons.

Replacing `;$` (read '; followed by a line ending') with `}` causes problems.

I tried to minify prototype.js code, i.e. the following snippet.

```javascript
(function() {
  window.Selector = Class.create({
    initialize: function(expression) {
      this.expression = expression.strip();
    },

    findElements: function(rootElement) {
      return Prototype.Selector.select(this.expression, rootElement);
    },

    match: function(element) {
      return Prototype.Selector.match(element, this.expression);
    },

    toString: function() {
      return this.expression;
    },

    inspect: function() {
      return "#<Selector: " + this.expression + ">";
    }
  });

  Object.extend(Selector, {
    matchElements: function(elements, expression) {
      var match = Prototype.Selector.match,
          results = [];

      for (var i = 0, length = elements.length; i < length; i++) {
        var element = elements[i];
        if (match(element, expression)) {
          results.push(Element.extend(element));
        }
      }
      return results;
    },

    findElement: function(elements, expression, index) {
      index = index || 0;
      var matchIndex = 0, element;
      for (var i = 0, length = elements.length; i < length; i++) {
        element = elements[i];
        if (Prototype.Selector.match(element, expression) && index === matchIndex++) {
          return Element.extend(element);
        }
      }
    },

    findChildElements: function(element, expressions) {
      var selector = expressions.toArray().join(', ');
      return Prototype.Selector.select(selector, element || document);
    }
  });
})();

function someOtherFunction() {
}
```

Which would minify to 

```javascript
(function(){window.Selector=Class.create({initialize:function(expression){this.expression=expression.strip()},findElements:function(rootElement){return Prototype.Selector.select(this.expression,rootElement)},match:function(element){return Prototype.Selector.match(element,this.expression)},toString:function(){return this.expression},inspect:function(){return "#<Selector: "+this.expression+">"}});Object.extend(Selector,{matchElements:function(elements,expression){var match=Prototype.Selector.match,results=[];for(var i=0,length=elements.length;i<length;i++){var element=elements[i];if(match(element,expression)){results.push(Element.extend(element))}}
return results},findElement:function(elements,expression,index){index=index||0;var matchIndex=0,element;for(var i=0,length=elements.length;i<length;i++){element=elements[i];if(Prototype.Selector.match(element,expression)&&index===matchIndex++){return Element.extend(element)}}},findChildElements:function(element,expressions){var selector=expressions.toArray().join(', ');return Prototype.Selector.select(selector,element||document)}})})()function someOtherFunction(){}
```

Which is invalid javascript, because of the missing semi-colon between the closure and the new function definition:

*Is*
`)}})})()function someOtherFunction(){}`

*Should be*
`)}})})();function someOtherFunction(){}`

Since this breaks scripts, it should be fixed asap.

**Comment by func0der** [comment]
The fix would be: 

```php
$content = preg_replace('/;(\})/s', '\\1', $content);
```

**Comment by matthiasmullie** [comment]
Hey @func0der - thanks for the report!

I added your example code to the test suite (see commit 574c4eef3a1cf2b7c2e7e40cc68a48c6721ce120), but I am not able to reproduce the issue - both on my own machine, or on Travis CI.
It minifies just fine for me, and leaves the `;` intact.

Any chance you were using an older version of the minifier? Can you try updating to latest master and see if the problem still occurs?

If it still fails, try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.

If the problem persists, feel free to reopen this ticket with some additional details (complete JS, PHP version, pcre config, ...)

**Comment by matthiasmullie** [comment]
Oh, I forgot to mention:

`$content = preg_replace('/;(\}|$)/s', '\\1', $content);` should be fine because it will only remove the `;`, but the `}` or `$` (end of line) will be preserved. So if a `;` followed by a newline is encountered, the `;` will be removed, but the newline will stay (and ASI will terminate the statement)
