### ISSUE TITLE
Removing quotes from url won't load file anymore !

### ISSUE THREAD

**Issue by Dexter-Andrei** [matthiasmullie/minify#193]
Ok:

This is one of my css rules:

`.swiper-button-prev{background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%2027%2044'%3E%3Cpath%20d%3D'M27%2C22L27%2C22L5%2C44l-2.1-2.1L22.8%2C22L2.9%2C2.1L5%2C0L27%2C22L27%2C22z'%20fill%3D'%23fff'%2F%3E%3C%2Fsvg%3E");right:10px;left:auto}`

And now optimized:

`.swiper-button-next,.swiper-container-rtl .swiper-button-prev{background-image:url(data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%2027%2044'%3E%3Cpath%20d%3D'M27%2C22L27%2C22L5%2C44l-2.1-2.1L22.8%2C22L2.9%2C2.1L5%2C0L27%2C22L27%2C22z'%20fill%3D'%23fff'%2F%3E%3C%2Fsvg%3E);right:10px;left:auto}`

As you see, the minify script removes the double quotes, and in this way the file won't be loaded.

Any fix for that ?

**Comment by matthiasmullie** [comment]
Hey @Dexter-Andrei - thanks for spotting this issue!
I just pushed a fix.
