### ISSUE TITLE
JS: 

### ISSUE THREAD

**Issue by hiersinddrachen** [matthiasmullie/minify#195]
Hi!
The JS minifier wrongly identifies the double slash in a URL as a comment. 
Here is an example code excerpt:
`"vimeo"==c.type?b="https://player.vimeo.com/video/"` 
The // is interpreted as a comment, thus the // and everything after it will be stripped, leading to broken JS.
This has worked in version 1.3.46, in 1.3.47 there must have been a change that lead to the problem described above.

**Comment by matthiasmullie** [comment]
Can you try again with 1.3.48 (pushed about an hour ago)?
If the problem still persists, can you post the full JS code? The little snippet you pasted works fine standalone, but the issue is probably caused somewhere else in the code.

**Comment by hiersinddrachen** [comment]
Yeah, we already tried 1.3.48 but the problem is still present.
Here a link to the code: https://pastebin.com/yGyq49Yn 
It is a minified, concatenated file with various JS libs/plugins.

**Comment by matthiasmullie** [comment]
Thanks for posting the full code!
I just improved regex detection and bunch, and I'm now able to minify your code without problem.
Please update to 1.3.49

**Comment by diolemo** [comment]
@matthiasmullie 

This seems to have been introduced with 1.3.48. 
I had to downgrade to 1.3.47 to get it working again. 

Example that breaks:

```
if (true || /^(https?:)?\/\//.test('xxx')) alert(1);
```

I will test 1.3.49 now (I just saw the commit as I was about to reply).

**Comment by hiersinddrachen** [comment]
@matthiasmullie Thank you very much! The new version fixes the problem - thanks for the quick update! :)
