### ISSUE TITLE
v1.3.50 Breaking Code

### ISSUE THREAD

**Issue by daerik** [matthiasmullie/minify#197]
After updating matthiasmullie/minify (`1.3.46` => `1.3.50`), I began getting "SyntaxError: unterminated regular expression literal" in my JavaScript. I rolled back to `1.3.46` to determine what caused the issue. The first issue that was reported came from `tinymce#4.6.6` using `tinymce.min.js`. I've included 2 screenshots: one from `tinymce.js` to highlight the affected code and `tinymce.min.js` (which I'm including in my project) to highlight the removed code (it goes down to the next new line).

I love your project. I hope this helps!

![image](https://user-images.githubusercontent.com/8672541/30402299-48e04942-98ab-11e7-95ea-d7b297d08d73.png)

![image](https://user-images.githubusercontent.com/8672541/30402311-4f1232b2-98ab-11e7-9dc5-8508273d3d65.png)

**Comment by matthiasmullie** [comment]
Hey @daerik (love your profile pic, btw) - thanks for noticing this!
Just pushed a fix.
