### ISSUE TITLE
Breaking changes in tag/1.3.48

### ISSUE THREAD

**Issue by reecube** [matthiasmullie/minify#198]
Some changes in the tag https://github.com/matthiasmullie/minify/releases/tag/1.3.48 are breaking my minified files. Everything works fine for the tag 1.3.47

I'll provide more/better information later, but I think you should know this.

**Comment by matthiasmullie** [comment]
Hey @reecube - Can you try again with 1.3.51, see if that works?
If not, please reopen this issue with a copy of the code that minified incorrectly, so I can reproduce and figure out what's wrong!

**Comment by reecube** [comment]
Something is still not working. My scripts are very big and the overhead of the application is very big also. Maybe it's something in the application, I could not reproduce the issue by myself without the application. In my case I will lock on the version 1.3.47. I just wanted to inform about possible breaking changes in projects using this library (I'm fine with locking).

Anyway, thanks a lot for your work on this library!
