### ISSUE TITLE
Need to fix comment stripping on JavaScript

### ISSUE THREAD

**Issue by alquerci** [matthiasmullie/minify#199]
Hello @matthiasmullie,

I use your library as it have a good code coverage with tests. But during utilization I caught that some comments are not striped as expected.

How to reproduce?
------------------------

For a quick tests put following comments on `tests/js/sample/line_endings/lf/script.js`.

```js
// This case was fixed on version 1.3.50
// function () { 
//    return false;
// };

// Next two cases failed since version 1.3.49
// function () { 
//    return false; //.click();
// };

// function () { 
//    ;//;
// }
```

Then execute `$ phpunit` and look at the test case `JSTest::minify`.

Results
---------

Expected result is that all comments are removed.
For PHP-5.6 and PHP-7.1 test results are the same.

| library version | test pass? | actual
| ------------------ | ------------ | -----------
| 1.3.47             | yes |
| 1.3.48             | yes |
| 1.3.49             | no | `//};//    return false; //.click();//};//;//}`
| 1.3.50             | no | `//    return false; //.click();//    ;//`
| 1.3.51             | no | `//    return false; //.click();//    ;//`

I need to require a stable version of your library to use is on production.

**Comment by matthiasmullie** [comment]
Hey @alquerci 
Thanks for the amazing reproduction details!
I just pushed a fix.

**Comment by alquerci** [comment]
@matthiasmullie Thank you so much for this quick fix.
