### ISSUE TITLE
make importing of graphics optional

### ISSUE THREAD

**Issue by matthes0815** [matthiasmullie/minify#203]
some of my large background images bloat the css when base64-encoded, it would be nice to have the option to switch the import off

**Comment by matthiasmullie** [comment]
Hey @matthes0815 

That is already possible, either by limiting the file types that get imported, or by limiting the max size of files to be imported:

```php
$minifier->setImportExtensions(array());
```
or
```php
$minifier->setMaxImportSize(0);
```

**Comment by matthes0815** [comment]
yeah, I had a look at your code and already tried both, but it didn't work.

`$cache = 'generic_cache_filename.css'
$minifier = new Minify\CSS();
$minifier->setImportExtensions(array());
$minifier->setMaxImportSize(0);
foreach($css_paths as $css) {
	$filename=$css;
	$minifier->add($filename);
}
$minifier->gzip($cache.'.gz');
$minifier->minify($cache);
$this->_brotli($cache);`

All graphics get imported, no matter what I do, bloating my css file to 500kb.
