### ISSUE TITLE
JS regex confused for a comment

### ISSUE THREAD

**Issue by kcookrunning** [matthiasmullie/minify#209]
I found that if a regular expression is placed into an array and contains a double slash `//` it is treated as a comment and is stripped.

Input:

`var my_regexes = [/[a-z]{3}\//g, 'a string', 1];`

Output:

`var my_regexes=[/[a-z]{3}\`

Expected Output:

`var my_regexes=[/[a-z]{3}\//g,'a string',1];`

**Comment by matthiasmullie** [comment]
Thanks for the report @kcookrunning! This is now fixed.
