### ISSUE TITLE
@media parse error

### ISSUE THREAD

**Issue by omicode** [matthiasmullie/minify#210]
If in css have empty media query result is wrong and browser can't parse it.
Example:

/*xs*/
@media (max-width: 767px) {
	.basket_ad{
		margin-top:0
	}
}
/*sm*/
@media (min-width: 768px) {}
/*md*/
@media (min-width: 992px) {}
/*lg*/
@media (min-width: 1200px) {}

Return:
@media (max-width:767px){.basket_ad{margin-top:0}@media (min-width:992px){}

**Comment by matthiasmullie** [comment]
Thanks for the report @omicode! This is now fixed.
