### ISSUE TITLE
Handle for empty while loops in JS minify

### ISSUE THREAD

**Issue by kcookrunning** [matthiasmullie/minify#211]
While loops in JS can also be empty with a trailing semi-colon

```
if (last){
  for(i=1;i<3;i++);
} else if (first){
  for(i in list);
} else {
  while(this.rm(name, check, false));
}
```
To catch the while loop case I added the following line to JS.php within the stripWhitespace() function

```
$content` = preg_replace('/(while\([^;\{]+\));(\}|$)/s', '\\1;;\\2', $content);
```

**Comment by matthiasmullie** [comment]
Thanks for the report @kcookrunning! This is now fixed.
