### ISSUE TITLE
Regex breaks css selector

### ISSUE THREAD

**Issue by unlocomqx** [matthiasmullie/minify#214]
This bit of code breaks the css selector and removes the white space

```
/\/|'/;
'.ctd_panel_content .ctd_preview';
```

Here's the output

```
/\/|'/;
'.ctd_panel_content.ctd_preview'
```

Is this a know issue? Was it fixed?
Thank you

**Comment by matthiasmullie** [comment]
Hey @unlocomqx - thanks for the report!

I added your example code to the test suite, but I am not able to reproduce the issue - both on my own machine, or on Travis CI.
It minifies just fine for me, and leaves the string intact.

Try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.

If the problem persists, feel free to reopen this ticket with some additional details (complete JS, PHP version, pcre config, ...)
