### ISSUE TITLE
Import CSS REGEX problem

### ISSUE THREAD

**Issue by martin-tichy** [matthiasmullie/minify#215]
Hello, in CCS regex @import is a mistake. When import contains encoded ampersands ('&' > '& amp ;') is there used semicolon. Regex select only part of the string. 
Can you repair the regex, please? Thank you

**Comment by matthiasmullie** [comment]
Thanks for the report @martin-tichy! This is now fixed.

**Comment by martin-tichy** [comment]
Thank you Matthias :-)
