### ISSUE TITLE
Pseudo elements, white space removal

### ISSUE THREAD

**Issue by peixotorms** [matthiasmullie/minify#216]
Hi there,

I'm using this on a wordpress plugin, and a user reported this issue:

> Here’s the issue – css minification algorithm removes spaces in “content” property of “:after” and “:before” pseudo-element.
> For example, I have such css rule:
> .link-wrapper a:before{content:"Click for Download";}
> After enabling css minification, “content” text becomes as “ClickforDownload” – without spaces.

Can you reproduce such behaviour?

**Comment by matthiasmullie** [comment]
Hey @peixotorms - thanks for the report!

I added your example code to the test suite, but I am not able to reproduce the issue - both on my own machine, or on Travis CI.
It minifies just fine for me, and leaves the string intact.

Try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.

If the problem persists, feel free to reopen this ticket with some additional details (complete JS, PHP version, pcre config, ...)
