### ISSUE TITLE
0px minification in calc()

### ISSUE THREAD

**Issue by boooklet** [matthiasmullie/minify#217]
Hi, this style in css:
`background: url("sprite.svg") calc(-192px * 1) calc(0px * 1) no-repeat;`
is being converted to:
`background:url(sprite.svg) calc(-192px * 1) calc(0 * 1) no-repeat;`

`calc(0 * 1)` return warning in browser and not working correctly. 

You can look at it.  Thank you.

**Comment by matthiasmullie** [comment]
Thanks for the report @boooklet! This is now fixed.
