### ISSUE TITLE
v1.3.56 Not Stripping *ALL* Comments

### ISSUE THREAD

**Issue by daerik** [matthiasmullie/minify#218]
Just did a fresh installation on a new project, so I don't have any previous versions to compare this issue with. However, I received "SyntaxError: missing } after property list" in my JavaScript and began debugging the issue. The issue resulted from `prismjs#1.9.0` using `prism.js`. I've included 2 screenshots: one from `prism.js` to highlight the affected code and `prism.min.js` to highlight the comment that remained in the code causing it to break the plugin.

It's interesting that this plugin uses single-lined comments everywhere, but they are all being removed. The only difference I've seen was that this comment was within an object.

I hope this helps!

EDIT: I knew I had used this plugin before without an issue, so I kept rolling back until I found the version which it worked with. `1.3.48` was the last version which correctly removed this comment.

![image](https://user-images.githubusercontent.com/8672541/33645754-640f631e-da1a-11e7-9a60-31621c23d491.png)

![image](https://user-images.githubusercontent.com/8672541/33645758-6960df64-da1a-11e7-8b42-04801adacc8c.png)

**Comment by matthiasmullie** [comment]
Thanks for the detailed report, @daerik! I just submitted a fix.
