### ISSUE TITLE
JavaScript minification "can" return FALSE

### ISSUE THREAD

**Issue by holtkamp** [matthiasmullie/minify#220]
This library does not (yet) use return types. A function I have which does use return types returned an error:

```php
private function minifyJavascript(string $javascript): string
    {
        $javascriptMinifier = new JavascriptMinifier($javascript);

        return $javascriptMinifier->minify();
    }
```

Returns
```
Return value of XYZ\MyScript::minifyJavascript() must be of the type string, boolean returned
```

This might occur because [substr()](https://github.com/matthiasmullie/minify/blob/7559ac0806f39f89f949c917e6612dda8154488b/src/JS.php#L182) can return false.

I guess this should either be:
- prevented: always return a string
- documented that "false" might be returned

**Comment by PeeHaa** [comment]
Or rather throw an exception

**Comment by matthiasmullie** [comment]
I indeed won't add return types as it would indeed break BC and compatibility with older PHP versions, but I assume just fixing the return value to always return a string (as documented) is all you need?
