### ISSUE TITLE
Regex like /…\// do break

### ISSUE THREAD

**Issue by leyyinad** [matthiasmullie/minify#221]
In commit 134b25a63d83a80ae128aedc9a99987e064b4382 (Release 1.3.57) [this](https://github.com/zloirock/core-js/blob/2b314f858005da33be07336f06be5cb790311529/modules/es7.string.pad-end.js#L8) [`core-js`](https://github.com/zloirock/core-js/)-module breaks, namely this expression:

```js
/Version\/10\.\d+(\.\d+)? Safari\//.test(userAgent)
```

The part beginning with `//.test…` is wrongly stripped.

**Comment by nosilver4u** [comment]
Just experienced something very similar on this JS file: https://www.ladmob.com/wp-content/themes/bimber/js/front.js?ver=5.3.1
where this line loses everything from the // going forward, and causes weirdness. I suppose it thinks there is a comment following, but it's part of a RegExp:
`new RegExp(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/)`
