### ISSUE TITLE
Successfully minified invalid JS

### ISSUE THREAD

**Issue by 0joshuaolson1** [matthiasmullie/minify#230]
`function(){})` -> `)`

**Comment by matthiasmullie** [comment]
It looks like you accidentally tried to minify that as CSS. The JavaScript minifier won't strip `function(){}`

**Comment by 0joshuaolson1** [comment]
Whoops, good catch. Is it intended behavior to say minification was successful if the JS is invalid?

**Comment by matthiasmullie** [comment]
Yeah - validity of the original code won't be checked at all, it'll just be minified as best as possible.
