### ISSUE TITLE
gaining a few more bytes

### ISSUE THREAD

**Issue by gnusam** [matthiasmullie/minify#232]
Hey, don't know if it is relevant for you, but i managed to scrap a few more Kb from my files adding some regexps into JS.php :

      $content = preg_replace('/}\nelse/', "}else", $content);
      $content = preg_replace('/}\ncatch/', "}catch", $content);
      $content = preg_replace('/}\nfinally/', "}finally", $content);
      $content = str_replace("}\n", "};", $content);
      $content = str_replace(")\nif", ");if", $content);
      $content = preg_replace('/{\n\$/', '{$', $content);
      $content = preg_replace('/,\n\$/', ',$', $content);
      $content = preg_replace('/\n\$/', ';$', $content);
      $content = preg_replace('/\)\n{/', '){', $content);
      $content = preg_replace('/\n{/', '{', $content);
      $content = preg_replace('/[\n]*\([\n]*/', '(', $content);
      $content = preg_replace('/{\n/', '{', $content);
      $content = preg_replace('/,\n/', ',', $content);
      $content = preg_replace('/\)\n\./', ').', $content);
      $content = preg_replace('/\n\)/', ')', $content);
      $content = preg_replace('/\)\n/', ');', $content);
      $content = preg_replace('/\n/', ';', $content);`

at line 361. 

My 2 cents.

**Comment by matthiasmullie** [comment]
Unfortunately, the `\n`-to-`;` replacements are not 100% safe to perform. E.g.:

```
if((!0)&&(!0))
something()
```
would become:
```
if((!0)&&(!0));something()
```

or

```
do{i++}
while(i<1)
```

turns into:
```
do{i++};while(i<1)
```

Both of these would end up correcting the source code.

I doesn't really matter too much whether there's a `\n` or `;` separating statements anyway: both are 1 byte. So I'm good with `\n` remaining `\n` :)

That said, there were a few useful lines in there as well, where `\n` could actually be stripped safely - I'm adding those :)
