### ISSUE TITLE
Error finding the Class.

### ISSUE THREAD

**Issue by SollyM** [matthiasmullie/minify#233]
Hi everyone. I am trying to implement minify and I have the below code and error. `Minify` folder is in the same as the index.php

**CODE:**

1. `<?php`
2. `require_once 'minify/src/Minify.php';`
3. `require_once 'minify/src/JS.php';`
4. `require_once 'minify/src/Exception.php';`
5. ` `
6. `use MatthiasMullie\Minify;`
7. ` `
8. `$cssMin = new Minify\CSS('assets/css/myCssFile.css');`

**Error in error_log file:**

`[23-Jan-2018 05:14:12 America/New_York] PHP Fatal error:  Class 'MatthiasMullie\Minify\CSS' not found in /home/johannes/public_html/2018/index.php on line 8`

How can I fix this problem?

**Comment by PeeHaa** [comment]
You never `include` / `require` the CSS class file. Either just use composer or include all the required files.

**Comment by SollyM** [comment]
Thank you ever so much. I thought those were the only Classes I needed. I didn't realise that there were more.
