### ISSUE TITLE
src/Minify.php - line 261 & 244

### ISSUE THREAD

**Issue by bravedave** [matthiasmullie/minify#245]
Hi

In the latest src/Minify.php at line 261 you have an unset
It causes an error at line 244 if the item is not set

I've rolled back to 1.3.58

if inserted a dump of the value and see this - (it errors when it itterates to 4):

> Array (
> [0] => 169
> [1] => 141
> [2] => 3398
> [3] => 3922
> [5] => -242
> )

let me know if I can help further

**Comment by msyk** [comment]
I met same issue. My quick fix is to replace line 261 from "unset($positions[$i]);" to "$positions[$i] = strlen($content);". Although I don't completely understand this code, the commit 04a37f5434c618cae16a7dca13592a567bc36246 could be reconsidered.

**Comment by bravedave** [comment]
Has that changed the intention of the loop ?

maybe a better quick fix would be to test at line 244
i.e. if ( !isset($positions[$i]) || $positions[$i] >= 0) {

but using composer it's easy enough to roll back - safer

**Comment by matthiasmullie** [comment]
Thanks for the heads-up guys - I had overlooked that! Just submitted another patch - can you test if this works?

**Comment by msyk** [comment]
Thanks! I try and current code works fine.

**Comment by bravedave** [comment]
Thanks - all good here too
Great utility Matthias - keep up the good work
Cheers
