### ISSUE TITLE
JS.php#L292 somehow crashes the site

### ISSUE THREAD

**Issue by peterwesterlund** [matthiasmullie/minify#254]
https://github.com/matthiasmullie/minify/blob/6d922d0e2a8b677abf41eb41e55792575ca2f529/src/JS.php#L292

This line somehow kills everything from after it's called. Comment it away and all seems to work. But probably not everything since what that line was supposed to do is not in use.

**Comment by matthiasmullie** [comment]
This is a pretty intensive regular expression, which might be consuming too much resources on your machine. I did slightly tweak the regex, though: can you try if 4762aedee61fd534bbcebd661af3662f29dcfb61 fixes this?
