### ISSUE TITLE
Css import files list

### ISSUE THREAD

**Issue by yr4ik** [matthiasmullie/minify#257]
There is no function to get list of imported files in css. This make caching problems. Add this function is not difficult. You can change Minify-> load.

**Comment by matthiasmullie** [comment]
Can you please clarify exactly what you would need and why you would need it?
I fail to understand the exact problem.
Closing the ticket as not actionable now, but please re-open with more details!

**Comment by yr4ik** [comment]
This is required for caching. Now if you process for example this css: 
```
@import "child.css";
@import "child2.css";

body {
	font-weight: bold;
}
.......
```

I can not get list of imported css (child.css and child2.css). And I can not get filelist for check their modification time.
