### ISSUE TITLE
Small percentages values problem

### ISSUE THREAD

**Issue by bbprojectnet** [matthiasmullie/minify#26]
Hi,

I found another bug, this CSS:

`	.hr > :first-child {
		width: 0.0001%;
	}`

is minified to:

`.hr>:first-child{width:001%}`

Should be:

`.hr>:first-child{width:0.0001%}`

**Comment by matthiasmullie** [comment]
Thanks!
Fixed in https://github.com/matthiasmullie/minify/commit/620f98fd09f03cf3a0ad96ff356a5c61e79f80c0
I've just pushed a new release that includes this fix.
