### ISSUE TITLE
Does this work like I add js or css file dynamically?

### ISSUE THREAD

**Issue by jun1432** [matthiasmullie/minify#263]
Does it detects changes on the source files and automatically included on the minified file?

Like the functionality of gulp watch or on webpack's watch.

**Comment by chetanmadaan** [comment]
Hello,

I think it would automatically pick up the latest version of the source files everytime you run it.

Unless you plan on saving the minified files (which you shouldn't), you should be fine by making changes to you source files and generating minified files on runtime.

**Not official author**

**Comment by matthiasmullie** [comment]
Actually, I would recommend to save the minified files & only run minify again if they have changed.
But that functionality is not included in here - it's something you'd have to check for yourself.
All this project does is minify whatever you throw at it, and how exactly you wish to incorporate that into your project is up to you entirely :)
