### ISSUE TITLE
Clip-path not working using url(#something)

### ISSUE THREAD

**Issue by synio-wesley** [matthiasmullie/minify#291]
When converting relative paths, `url(#something)` also gets a new path, but this should be unchanged! Otherwise `clip-path: #something` won't work anymore! Can this be fixed?

**Comment by MathieuLoras** [comment]
in CSS.php line 434 add  
if(preg_match('/^#/',$url))continue;

**Comment by synio-wesley** [comment]
Thanks for looking into it. I'm closing this because it's > 1.5 years old and I'm not sure if the problem still exists today.

**Comment by elabx** [comment]
I can confirm the issue is still there.

**Comment by SharakPL** [comment]
Ping @matthiasmullie 🙏
