### ISSUE TITLE
Deprecation warning in PHP7.4

### ISSUE THREAD

**Issue by ildar-aim** [matthiasmullie/minify#293]
```
[16-Sep-2019 18:30:34] Unknown Error: implode(): Passing glue string after array is deprecated. Swap the parameters in lib/vendor/matthiasmullie/minify/src/CSS.php on line 528 
Backtrace:
    lib/vendor/matthiasmullie/minify/src/CSS.php:528
    lib/vendor/matthiasmullie/minify/src/CSS.php:314
    lib/vendor/matthiasmullie/minify/src/Minify.php:111

```

https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix

**Comment by alfonso100** [comment]
We have a couple of cases too. Deprecation notices for users who are migrating to PHP 7.4:
`[11-Dec-2019 09:15:38 UTC] PHP Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in/wp-content/plugins/wp-rocket/vendor/matthiasmullie/minify/src/CSS.php on line 528`

**Comment by matthiasmullie** [comment]
Sorry for letting this slip for too long! Pull request has been merged, and I'll push a new release later today!
