### ISSUE TITLE
Broken minified files when one source file doesn't exists

### ISSUE THREAD

**Issue by enricodias** [matthiasmullie/minify#296]
When adding several files to be minified either by the constructor or using the `add()` method, the function assumes that the argument is a plain css/js code if it fails to load a file. This results in broken code since the file path is added to the minified code.

This is especially common when working with several dynamic js/css files. When it happens, no error occurs and no exception is thrown. It fails silently and without warning the developer.

I propose a new method `addFile()` that expects only file names in its arguments and fail if a file is unreadable.

**Comment by enricodias** [comment]
Associated PR [#297](https://github.com/matthiasmullie/minify/pull/297)

**Comment by hscheffknecht** [comment]
I just wasted a lot of time because of this issue. Could somebody please merge this PR?
