### ISSUE TITLE
Javascript minimize

### ISSUE THREAD

**Issue by nerijuso** [matthiasmullie/minify#30]
Hi. 
I have many scripts on website and add all of them to minimize. One of these scripts is jquery 2.1.0v After you libriray minimize jquery I get error.
Error:
SyntaxError: missing name after . operator
...c[b]||[]).concat(cc.*),f=0,g=e.length;g>f;f++)if(d=e[f].call(c,b,a))return d}fu

My minimized jquery you can find here http://nerijuso.lt/test.js

**Comment by matthiasmullie** [comment]
I think https://github.com/matthiasmullie/minify/commit/e2ee427f26457ad99a74e3cb1488975c8cf66a43 should fix this - any chance you could try & confirm?

**Comment by nerijuso** [comment]
Yes. It works now! Thank you ;)
