### ISSUE TITLE
Imported css files are not included in the minified version

### ISSUE THREAD

**Issue by nevrologica** [matthiasmullie/minify#304]
Using the following code

```
<?php

header('Content-type: text/css');
header('Cache-Control: max-age=31536000');

$path = '../lib';
require_once $path . '/minify/src/Minify.php';
require_once $path . '/minify/src/CSS.php';
require_once $path . '/path-converter/src/ConverterInterface.php';
require_once $path . '/path-converter/src/Converter.php';

use MatthiasMullie\Minify;

$minifier = new Minify\CSS();

$minifier->setMaxImportSize(10);

$minifier->add('style.css');

echo $minifier->minify();

?>
```

I can see that the minified version that comes out will not include @import url(https://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300) into the main file, nor it changes it into @import "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300".

The import is 7KB, even if i setMaxImportSize(100) it will still not include it. There is no Exception coming out either.

**Comment by matthiasmullie** [comment]
Only local files will be included - external imports will remain untouched.

**Comment by nevrologica** [comment]
Makes sense. It would be a nice feature to fetch external files though into a bundle and optimize completion time client-side, since external imports usually don't change much and i am only minifying all files once at the back-end and then serving them straight from memcached.
