### ISSUE TITLE
calc incorrectly minified

### ISSUE THREAD

**Issue by castles** [matthiasmullie/minify#312]
We also have a similar issue where this:

`.alignfull { width: calc(100% + calc(2 * var(--central-padding))); }`

is being minified to this:

`.alignfull{width:calc(100% +)calc(2 * var(--central-padding)))}`

**Comment by rhukster** [comment]
Can confirm this. Working with TailwindCSS and it has some useful "space between" helper classes (https://tailwindcss.com/docs/space#add-horizontal-space-between-children) which generates CSS like:

```
margin-left: calc(0.5rem * calc(1 - var(--space-x-reverse)));
```

However, when minify'ing with latest releae version of this library, this results in:

```
margin-left: calc(0.5rem *)calc(1 - var(--space-x-reverse)));
```

Which is incorrect and results in invalid CSS.

**Comment by rhukster** [comment]
Any word on this?  the issue keeps coming up especially now that it's used in TailwindCSS for `space-x` and `space-y` utilities: https://tailwindcss.com/docs/space

**Comment by Narno** [comment]
@matthiasmullie 👍

**Comment by rhukster** [comment]
👍🏻 Thanks!
