### ISSUE TITLE
Uncaught SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by Pixeltechniker** [matthiasmullie/minify#32]
I try to minify Bootstrap, Boostrap Toggle and Chart.js and get the following Error:

Uncaught SyntaxError: Unexpected token *

**Comment by Pixeltechniker** [comment]
I also get Uncaught SyntaxError: Unexpected identifier errors. Maybe a problem with jQuery's noConflict mode i use?

**Comment by matthiasmullie** [comment]
Any chance you could post the incorrectly minified code in here? Preferably just the part that is causing breakage, along with the original source - but just full source may already be useful too.

**Comment by matthiasmullie** [comment]
I've tried minifying all 3 of those libraries. It appears the problem is the same as what's reported in issue #33. I'll close this one. For updates, see issue #33
