### ISSUE TITLE
JavaScript file minification getting error

### ISSUE THREAD

**Issue by ghazispeakserve** [matthiasmullie/minify#33]
Hi there,

When I minify bootstrap.js I get the following browser error.

```
SyntaxError: missing ; before statement
$.fn.alert=Plugin $.fn.alert.Constructor=Alert
```

I have joined the original file, the minified one and a third one mifnied by http://www.jsmini.com which works when used in the project.

After comparing both compressed files it seems like the issues is coming from missing line returns between variables declarations.

Files are here : https://www.dropbox.com/sh/lwxo2pmap6z8xuu/AADc-Y1gNH493bk1qEn5UBYfa?dl=0

**Comment by matthiasmullie** [comment]
This issue should be fixed with [this commit](https://github.com/matthiasmullie/minify/commit/3e997eb9b32ea07842dcc6acdb48bf4f32c9019b). I'll push a new version that includes the fix.
