### ISSUE TITLE
How do you use this without Composer??

### ISSUE THREAD

**Issue by chris98** [matthiasmullie/minify#339]
As the title says, I'm trying to include this without Composer but I can't get anything to work. Any ideas how I might be able to get it working?

**Comment by jp-onsite** [comment]
you can download everything to your local development machine with composer. After that you can copy everything to your target system. you dont need composer on the target system. require '/libs/autoload.php'; in your php code before working with minifier

**Comment by matthiasmullie** [comment]
This should work: https://github.com/matthiasmullie/minify/issues/83
