### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier with Moment.js 2.9.0

### ISSUE THREAD

**Issue by Pixeltechniker** [matthiasmullie/minify#34]
I try to minify moment-with-locales.min.js v.2.9.0 from http://momentjs.com/ and get the following error:
"Uncaught SyntaxError: Unexpected identifier"

**Comment by matthiasmullie** [comment]
Confirmed - I'm able to reproduce this one. Looks like it isn't properly extracting string (causing content inside the string to be seen as code)

**Comment by matthiasmullie** [comment]
Fixed in https://github.com/matthiasmullie/minify/commit/471f982e63ac54ec2e3167dc05029c2777b77bdd

**Comment by matthiasmullie** [comment]
Released 1.3.17 to include this fix.
