### ISSUE TITLE
JS: URL in string is (wrongly) handled as inline-comment

### ISSUE THREAD

**Issue by Idrinth** [matthiasmullie/minify#347]
```js
new A(
  '<meta charset="utf-8" xmlns="http://www.w3.org/1999/html">',
  '<table '
)
```
Leads to
```js
new A('<meta charset="utf-8" xmlns="http:'<table ')
```
The example has been shortened a bit to keep it readable.

**Comment by matthiasmullie** [comment]
This is a JS & CSS minifier - that code in there is HTML is not intended to be understood by this library and trying to minify it is expected to product incorrect results.
