### ISSUE TITLE
Uncaught SyntaxError: Unexpected token * with comments at the end of a file

### ISSUE THREAD

**Issue by Pixeltechniker** [matthiasmullie/minify#35]
Theres an issue with comments at the end of a file. For example:

jQuery(document).ready(function($) {
  // do your stuff
});
// the bad comment

The last comment is causing an Unexpected token * Syntax Error.

**Comment by Pixeltechniker** [comment]
I tried to minify Bootstrap Toggle (http://www.bootstraptoggle.com) and holder.js (http://imsky.github.io/holder). With the current master i get a different error: "Uncaught SyntaxError: Unexpected identifier". It seems that not all comments are removed in this file.

Minified file: http://www.file-upload.net/download-10261212/scripts.js.html

**Comment by matthiasmullie** [comment]
It took me awhile to figure out what went wrong here. I couldn't reproduce it as my IDE keeps adding an empty newline at the end of every file.

Anyway: when a script ends in a single-line comment & the next script is joined, it doesn't start at a newline, just right behind the previous script. Which results in it being part of the single-line comment, right until the next \n

https://github.com/matthiasmullie/minify/commit/5d1886a2ef0c48a9aa51695082fd2c0fbd32a4b5 should fix this problem. Released 1.3.18

**Comment by Pixeltechniker** [comment]
Working perfect. Thank You!
