### ISSUE TITLE
@import not treated right

### ISSUE THREAD

**Issue by webbird** [matthiasmullie/minify#38]
I am trying to minify a bunch of CSS files like so:

    if(count($files))
        foreach(array_values($files) as $file)
            $minifier->add($file);

...where `$files` is an array of local file names (=paths, not URIs).

The first file contains a list of `@import`s, which are resolved the wrong way. Result is:

    @import url(../P:/apache/htdocs/...more.../reset.css);

I would expect either an URL or that the imported file is read an minified too. Of course, returning an URL is not that easy, as the class would have to guess the URL from the path. (Or allow to set a BaseURL as a config param.) Anyway, better way would be to replace the imports with the minified contents of the files. Could be done quite easily by checking for local files with `file_exists()`.

I have a workaround I got from another class (https://github.com/dg/ftp-deployment/blob/v1.1/Deployment/libs/Preprocessor.php#L63), but you may like to have a look at this. Maybe I am doing something wrong?

**Comment by webbird** [comment]
Found that I need to give a $path when calling `minify()` to solve this. But in this case, a file is created in the path, which is not desired here. Is there a way to solve this without creating a new file?

**Comment by matthiasmullie** [comment]
Well, if we're not creating a new file, the minifier has no idea what to change the relative paths to.

Which means it can:
* convert all of them to absolute paths (which makes no sense because absolute paths on the machine where minifier runs will not be the same as the URIs it'll have to be)
* not convert them at all

I think the latter makes most sense, what do you think?

**Comment by matthiasmullie** [comment]
Patch to not convert relative paths unless there is a new path to write to, is at https://github.com/matthiasmullie/minify/commit/677997cd55d6c9a7cab8c7254619fa0f1c781973

I'll close this as resolved. If you think it's not, feel free to reopen!

**Comment by webbird** [comment]
I understand the problem, but it could be solved by allowing to pass a "BaseURL" if no output path is given.

**Comment by matthiasmullie** [comment]
@webbird: can you elaborate on why you would need that? As far as I can tell, if you're not saving the file anywhere, it doesn't actually really matter what the paths are anyway?

I'm not saying I won't implement it, but it would make the method signature of CSS's minify different than abstract Minify's, and I'm not going to do that unless there's a really good reason for it :) or we can figure out another solution. I just want to understand the usecase!

**Comment by webbird** [comment]
Not really to be honest. :D It may be a consequence of doing performance tests while searching for a 'perfect' solution. Also, in some environments it may not be allowed to write into the source folder. (By file system permissions.) But I think in this case the on-the-fly-minification would just eat up the positive effects of minified files. So it seems to be just a matter of not thinking it out.

**Comment by matthiasmullie** [comment]
Oh, well I'm actually pretty glad you don't have a great usecase either - then I don't have to implement that (yet) :)
But thanks for the testing and the report on the incorrectly handled relative paths when not saving the file somewhere!

**Comment by webbird** [comment]
Thank you very much for your support. (And for helping me thinking that to the end. *smile*)
