### ISSUE TITLE
Class 'MatthiasMullie\Minify\CSS' not found

### ISSUE THREAD

**Issue by hobodi** [matthiasmullie/minify#398]
Hi,
we enabled our pagespeed module after a while and got the following error:

Array
(
    [type] => 1
    [message] => Class 'MatthiasMullie\Minify\CSS' not found
    [file] => /var/www/clients/client2/web21/web/app/code/local/MageAssist/Pagespeed/Model/MatthiasMullie/Minify/CSS.php
    [line] => 3
)

I don´t know what happened but until we disabeld the module everything works fine. Can someone help us please?

**Comment by matthiasmullie** [comment]
Can you please elaborate about what that pagespeed module is?

**Comment by hobodi** [comment]
Hi Matthias, we fixed it. We had an issue with a patch for the autoloader. So we can close this ticket, thx.
