### ISSUE TITLE
text onchange in the script

### ISSUE THREAD

**Issue by ammahir** [matthiasmullie/minify#400]
It throws error if my script contains onchange text.
eg. var a="<input type='text' onchange='abc()' />"

>> Something, somewhere, somehow failed! Did you post a link to an unreachable script?
![image](https://user-images.githubusercontent.com/418687/202122239-6cc7f8da-ee91-4737-ab50-e49b093d2de7.png)

**Comment by matthiasmullie** [comment]
That domain (minifier.org) is not associated with this project (it used to be at some point in the past, but I got rid of it to reduce the amount of things I need to spend time to maintain)

Whatever is going on is not the result of a bug in this project.

I will ask the current owner of the domain to get rid of things that make it look like it is still associated with this project, but there's nothing we can fix from here.
