### ISSUE TITLE
IE8 JavaScript minifing error

### ISSUE THREAD

**Issue by bbprojectnet** [matthiasmullie/minify#41]
I think, JS minifier shouldn't replace this:
`conf.zoomHoverIcons['default']`

to:
`conf.zoomHoverIcons.default`

It's cause error in IE8 browser.

**Comment by matthiasmullie** [comment]
You're right. The problem is with 'default' being a reserved word - others appear to work just fine with IE8.

**Comment by matthiasmullie** [comment]
Above patch fixes that! I'll push a new release tomorrow.

**Comment by bbprojectnet** [comment]
And as always, thanks a lot :)
