### ISSUE TITLE
Waiting for the new version

### ISSUE THREAD

**Issue by vanushwashere** [matthiasmullie/minify#412]
I encountered a performance loss on some websites because of Minifier, and after a little bit research I found out that there were many performance fixes on the `master` branch. 
Are you planning to release the new version?

**Comment by vanushwashere** [comment]
I checked that website with the version from the master branch and it still had a very big performance loss(like 20s instead of 1s). :(

**Comment by matthiasmullie** [comment]
Thanks for pointing this out - I had not realized I must've forgotten about the release when last landing changes.
Release coming soon.

**Comment by matthiasmullie** [comment]
Done - released 1.3.71

**Comment by vanushwashere** [comment]
It's fixed the performance issues, but strange. I tested `master` branch yesterday and still had them. 
Anyway, thanks for the fast response and useful package. 
I was thinking, maybe adding some settings to bypass removing comments would be helpful for such cases. Would you like a PR ?

**Comment by matthiasmullie** [comment]
Alas; comments will need to be extracted either way - otherwise, comments that contain code (or stuff that looks like it) in them may affect the rest of the minification.

**Comment by vanushwashere** [comment]
Yeah, but I mean it might be helpful to skip some optimization in favor of overall speed and performance.
