### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by mkeryeski** [matthiasmullie/minify#42]
use MatthiasMullie\Minify;

require_once 'minify/Minify.php';
require_once 'minify/JS.php';
$minifier = new Minify\JS('alert("hello")');
echo $minifier->minify();

Produces this:
<br />
<b>Catchable fatal error</b>:  Argument 1 passed to MatthiasMullie\Minify\JS::getOperatorsForRegex() must be of the type array, boolean given, called in /var/www/xxx.com/public_html/common/minify/JS.php on line 216 and defined in <b>/var/www/xxx.com/public_html/common/minify/JS.php</b> on line <b>300</b><br />

I can use the CSS minifier fine with my CSS code. Can you figure out what's going wrong?

**Comment by mkeryeski** [comment]
For anyone checking, the issue was I was missing those text files in the js/data directory

**Comment by matthiasmullie** [comment]
Great to see you figured it out already :)

**Comment by mkeryeski** [comment]
Can you check to see why I am getting javascript errors after minifying this? http://www.hdrrocks.com/js/master.js

**Comment by matthiasmullie** [comment]
@mkeryeski I think your problem should be fixed with https://github.com/matthiasmullie/minify/commit/0ada1eccaf2566b30f9021d613a2cae9e4e00f4d

Any chance you could try that out?

**Comment by mkeryeski** [comment]
works great. thanks for the quick support

**Comment by mkeryeski** [comment]
Hi again. Perhaps you could look at this one when you get a chance? http://big80smetal.hdrn9.kicks-ass.net/js/master.js Thanks again.

**Comment by mkeryeski** [comment]
Hi - having another issue, can you look at my script again? http://hdrrocks.com/js/master.js thanks in advance

**Comment by matthiasmullie** [comment]
@mkeryeski Should be fixed with: https://github.com/matthiasmullie/minify/commit/ecd1a04d886896bc3f42b4cfc418f8659800a242

I'll try to push a new release with this fix later today
