### ISSUE TITLE
propertyNotation incorrectly converts stand-along array

### ISSUE THREAD

**Issue by silentmiles** [matthiasmullie/minify#44]
I have code that includes the following:

return ["x"];

Minify is incorrectly converting this to the following:

return .x;

**Comment by matthiasmullie** [comment]
Thanks for reporting the issue! https://github.com/matthiasmullie/minify/commit/e15f77b7f6ce4c54bb566934984e4c0cc8931ee4 should fix this.
I'm about to push a new release (1.3.23) with both fixes.
