### ISSUE TITLE
Minify::restoreExtractedData regex compilation failing

### ISSUE THREAD

**Issue by silentmiles** [matthiasmullie/minify#45]
I'm getting the following error:

preg_replace_callback(): Compilation failed: regular expression is too large at offset 47638 in Minify.php on line 353

I think this is occurring because the Javascript that's being minified in this case happens to already be minified, so appears as one long line.

Unfortunately, I'm not in control of the input, so don't know when the source is already minified.

**Comment by matthiasmullie** [comment]
@vladimmi fixed this issue in https://github.com/matthiasmullie/minify/pull/46
I'm about to push a new release (1.3.23) with both fixes.
