### ISSUE TITLE
use minify without composer

### ISSUE THREAD

**Issue by Flaschenzug** [matthiasmullie/minify#48]
Hey,

just a short question. Is it possible to use your Minify Application without composer?
I tried it but i don't find a way to make it work.

Thanks for your help.
Kind Regards and good night.

**Comment by matthiasmullie** [comment]
Hi,

It's definitely possible. Just include the 4 source files:

```php
require_once $path . '/minify/src/Minify.php';
require_once $path . '/minify/src/CSS.php';
require_once $path . '/minify/src/JS.php';
require_once $path . '/minify/src/Exception.php';
```

**Comment by Flaschenzug** [comment]
Thanks for the quick reply.

I tried it the way that you explained, but I can't find a way to make it work.

require '../system/minify/src/Minify.php';
require '../system/minify/src/CSS.php';
require '../system/minify/src/JS.php';
require '../system/minify/src/Exception.php';
use MatthiasMullie\Minify;

$sourcePath = '../../../css/slacklineshop.css';
$minifier = new Minify\CSS($sourcePath);

But i get this error:
Fatal error: Class 'MatthiasMullie\PathConverter\Converter' not found in /system/minify/src/CSS.php on line 292

Any ideas ? Thanks

**Comment by matthiasmullie** [comment]
Right, I forgot I recently split that out into a separate repo, which you'll also have to clone: https://github.com/matthiasmullie/path-converter

Then also require this file:

```php
require '../system/path-converter/src/Converter.php';
```

**Comment by Flaschenzug** [comment]
Great, now its working !!!
I will integrate it and than post my complete code - so it might help someone else.

Thanks for the great work matthias. :+1:

**Comment by w3l** [comment]
This was extremely useful. I have never used "Composer" so I would encourage @matthiasmullie to add this information to README.md.

**Comment by matthiasmullie** [comment]
I've linked to this issue form README.md (https://github.com/matthiasmullie/minify/commit/f1005c691896e8d0a676db3c0aa1656bb4ad346b)

**Comment by natsouk** [comment]
Hello all and thanks for your work matthias.
I have make this : 
require_once 'minify/Minify.php';
			require_once 'minify/CSS.php';
			require_once 'minify/JS.php';
			require_once 'minify/Exception.php';
			require_once 'minify/Converter.php';
			use MatthiasMullie\Minify;
and i have this error : Parse error: syntax error, unexpected T_USE

do you know how i can resolve it please?
Thanks in advance :)

**Comment by matthiasmullie** [comment]
Hi @natsouk - any change you put that code inside a function? Use statements should be in the global scope (so probably at the top/bottom of your file). See http://stackoverflow.com/questions/18227439/use-php-namespace-inside-function

**Comment by natsouk** [comment]
Thanks a lot.
All is ok now.
I use it on my website and it work perfectly 
Thanks again.




Benoît R.
(France) +33 366 721 943
(Belgique) +32 494 90 12 49
http://www.happyfete.com

**Comment by kije** [comment]
You should mention, that the files under data/js are also required when using minify without composer ;-)

**Comment by prakashnnpatel** [comment]
I tried to implement minify without composer but i got Fatal error like **Fatal error: Interface 'MatthiasMullie\PathConverter\ConverterInterface' not found in ....**

i tried same as describe in below article
http://ourcodeworld.com/articles/read/350/how-to-minify-javascript-and-css-using-php

Dir Structure:
-www/test/minify-test/minify
-www/test/minify-test/path-converter

My code: (www/test/minify-test/index.php)
<?php
$path = $_SERVER['DOCUMENT_ROOT'].'/test/minify-test';
require_once $path . '/minify/src/Minify.php';
require_once $path . '/minify/src/CSS.php';
require_once $path . '/minify/src/JS.php';
require_once $path . '/minify/src/Exception.php';
require_once $path . '/path-converter/src/Converter.php';

use MatthiasMullie\Minify;

$sourcePath = $_SERVER['DOCUMENT_ROOT'].'/js/test1.js';
$minifier = new Minify\JS($sourcePath);

$sourcePath2 = $_SERVER['DOCUMENT_ROOT'].'/js/test2.js';
$minifier->add($sourcePath2);

$js = 'var test = 1';
$minifier->add($js);

// save minified file to disk
$minifiedPath = $_SERVER['DOCUMENT_ROOT'].'/test/minify-test/file.js';
$minifier->minify($minifiedPath);

// or just output the content
echo $minifier->minify();
?>

**Comment by matthiasmullie** [comment]
Hey @prakashnnpatel 

Since that post you linked, there have been a few changes to minify & path-converter library and some other files need to be included as well.
Up-to-date instructions for including minify without composer can be found here: https://github.com/matthiasmullie/minify/issues/83

I'll try to reach out to ourcodeworld.com to notify them about these changes and hopefully get them to update the instructions as well.

**Comment by matthiasmullie** [comment]
The article on http://ourcodeworld.com/articles/read/350/how-to-minify-javascript-and-css-using-php has also been updated!

**Comment by prakashnnpatel** [comment]
Thanks @matthiasmullie , it is working now!!!

**Comment by prakashnnpatel** [comment]
How to Enable gzip compression for js and css ?

**Comment by matthiasmullie** [comment]
You can either configure your server to serve files zipped, like with this config for apache2:

```
<IfModule mod_deflate.c>
	AddOutputFilterByType DEFLATE text/javascript text/css application/x-javascript application/javascript
</IfModule>
```

Or you can have this minifier save the files zipped (but then you'll have to take care of detecting if the browser accepts gzip, and make sure you set the correct output headers):

```php
$minifier->gzip($path);
```

**Comment by TooLogic** [comment]
Hi Mathias.
I got PHP Fatal error:  Cannot redeclare MatthiasMullie\\Minify\\Minify::minify()
wordpress theme using a lot of plugins, where (posible) is method minify(). What to do?

**Comment by aquasoft** [comment]
Hello Matthias. I have a question. How can I implement the transfer of multiple files for minimization without listing them? Is it possible to specify a directory as an input parameter, for example: ../path/css or js
