### ISSUE TITLE
Replacing while with for in JS may cause errors

### ISSUE THREAD

**Issue by phlorie** [matthiasmullie/minify#50]
Hi

I just ran into a problem with the JS minification.
It replaces 'while(true)' or similar with 'for(;;)', which breaks the code when it is a (do while).

In my case the code was :
do{var dim=this._getDaysInMonth(year,month-1);if(day<=dim){break}month++;day-=dim}while(true)}

And doesn't work when it becomes:
do{var dim=this._getDaysInMonth(year,month-1);if(day<=dim){break}month++;day-=dim}for(;;)}

**Comment by matthiasmullie** [comment]
Hi @phlorie 

I just pushed a patch (90837a68860a9935d1104e7fdd2c839967f52225) that should fix this problem.
I'll include it in the next release, which I'll be pushing in a couple of days.

Thanks!
