### ISSUE TITLE
Cache?

### ISSUE THREAD

**Issue by phlorie** [matthiasmullie/minify#51]
Hi

I couldn't find any information about this.
Is the resulting file cached somehow or is the minification executed every time someone loads the page?

Thanks

**Comment by PeeHaa** [comment]
It is not automagically cached. However writing a thin layer on top of this project to enable caching is trivial.

As a matter of fact I have done just [that](https://github.com/PeeHaa/Minifine) recently for my specific use case. Basically the onyl thing you need to do is store the combined and minified content somewhere (file / mem / whatever).

**Comment by matthiasmullie** [comment]
The result is not cached. All this does is minify.
How the minified result is handled is up to whoever implements this.
->minify() accepts a $path parameter to let you store the minified result to a file.
Typically, you would probably compile all your files when deploying, and let your HTML include that minified file.

Or look at @PeeHaa's solution. Seems like he's built a generic service that pretty much does what you need already.

-

This is probably out of scope for your question, but if you're looking to integrate with cache, I just pushed 49a2aca2945d6792dffb152e1aae9f1579eeb798. Similar to how ->minify($path) writes to file, ->cache($item) will write the result to a PSR-6 CacheItemInterface object.
