### ISSUE TITLE
JS Minification generates error

### ISSUE THREAD

**Issue by binarygeotech** [matthiasmullie/minify#54]
I bumped into this PHP minification library and tried to check it out, But I noticed and error when trying to minify some javascripts libraries like **```pjax```**, which can be found here ``` https://github.com/defunkt/jquery-pjax ```.
After checking the code, I noticed there are some statements ending without ``` ; ``` symbol which generates error after combination and minification.
I will be glad if this can be fixed.

**Comment by matthiasmullie** [comment]
Hi @binarygeotech & thanks for the bug report.

This issue should be fixed with https://github.com/matthiasmullie/minify/commit/5497bea3d1e25d14091a9dcb45a3aa326e4090f7
Any chance you could confirm this works? I'll release a new version in a couple of days then.

**Comment by binarygeotech** [comment]
Yeah, It fixed the issue like charm.
Looking forward to get the latest version with the fix.

Also, I got issue with Minifying assets on the fly, which I'm able to solve by creating an avenue to provide website **base url** and it worked like charm.

Thanks

**Comment by matthiasmullie** [comment]
Just pushed the new release: 1.3.27
