### ISSUE TITLE
Regex without quotes and semicolon appended to next line

### ISSUE THREAD

**Issue by WouterSioen** [matthiasmullie/minify#56]
This code:

```
var timeRegex = /^([2][0-3]|[01]?[0-9])(:[0-5][0-9])?$/
if (start_time.match(timeRegex) == null) {}
```

Gets minified to

```
var timeRegex=/^([2][0-3]|[01]?[0-9])(:[0-5][0-9])?$/if (start_time.match(timeRegex) == null) {}
```

There should be a semicolon added in between the two lines.

I know that it's a best practice to use semicolons in JavaScript, but it's still valid without them, so the minifier should be able to handle it.

**Comment by matthiasmullie** [comment]
Fixed with 4cf2880e51b639ee8a4f59cd877827efe966e0b0

**Comment by WouterSioen** [comment]
Great, thx!

**Comment by GinoPane** [comment]
Sorry, but is it really fixed? There's no semicolon even in test case.

**Comment by matthiasmullie** [comment]
The problem was that the newline was stripped completely, which in this case was not allowed.
The indeed is no semicolon after the fix, but a `\n` instead, which is also just 1 char.
