### ISSUE TITLE
Regex issue

### ISSUE THREAD

**Issue by GM-Alex** [matthiasmullie/minify#59]
If you have a function like that 

```javascript
isPath:function(e) {
    return /\//.test(e);
}
```

the regex is converted to ```/\```. Which causes in an error. The example is taken from jquery mobile.

If you store first the regex to some value and execute the function against the value it works like expected

```javascript
isPath:function(e) {
    var r=/\//;
    return r.test(e);
}
```

**Comment by matthiasmullie** [comment]
Fixed with c37967744d3d21793d6676581afff77458fcde0d
