### ISSUE TITLE
shortenZeroes Bug

### ISSUE THREAD

**Issue by BlkChockr** [matthiasmullie/minify#60]
Hey there, 

I just noticed that Safari does not like it if you strip out the 'px' from '0px'...

When I comment the line where this happens out in your source code, Safari behaves like it should.

In my case this happened most often with transitions, translations, etc..

Maybe you find a better solution, but I for myself will just use this workaround until then :)

**Comment by matthiasmullie** [comment]
Hi @BlkChockr 

Thanks, I wasn't aware of that.
Do you have some more details, though? I can't find anything about this behavior.
What version of Safari are you running? Do you have an example of a CSS statement where it seems to fail?
Any additional information that can help me understand what statements/params may be exhibiting this problem would help :)

**Comment by BlkChockr** [comment]
Hello again,

my Safari Version is 8.0.6, running on OSX 10.10.3. I know that this also happens on iOS, as this was where a colleague of mine noticed it first.

I cannot give you a specific code piece (I switched project-teams at work), but I realized this when comparing "your" minified version of our stylesheets against one from http://csscompressor.com (with which it worked) in http://text-compare.com . :)

The site on which this occured was http://www.traum-ferienwohnungen.de/suche.htm in the mobile version (just reduce the window size). Maybe you can compare the css on there against the one your current code generates. Then you would have one version with and one version without zeroes...

I'm sorry I can't help that much, but I'm writing this from work and don't have time to set up a testing-environment for now. :(

**Comment by matthiasmullie** [comment]
Thanks for the extra info, @BlkChockr - helped me figure out what the problem was.
It turns out Safari (and to a lesser extend, Chrome too) doesn't see '0' and '0%' and the same thing.
I've changed things to only omit the 'px' unit for now. Maybe at some point we'll be able to omit the rest as well.
Thanks for the report! Please let me know if this adequately fixed your problem ;)

**Comment by BlkChockr** [comment]
It seems to be fixed! :)

Another colleague of mine will test it next week, but for me it looks like everything is working.

**Comment by matthiasmullie** [comment]
Perfect. Thanks for confirming!
