### ISSUE TITLE
Catchable fatal error in Minify\JS

### ISSUE THREAD

**Issue by kije** [matthiasmullie/minify#65]
Im getting the following error when compressing JavaScript:

	Catchable fatal error: 
	Argument 1 passed to MatthiasMullie\Minify\JS::getOperatorsForRegex()  must be of the type array, 
	boolean given, called in /home/httpd/vhosts/awk.ch/httpdocs/inc/minify/JS.php on line 221 
	and defined in /home/httpd/vhosts/awk.ch/httpdocs/inc/minify/JS.php on line 321

Even when I'm compressing no JS file at all (directly call ->minify(), without passing any path or JS to the minifier), this error occurs.

**Comment by matthiasmullie** [comment]
Hi @kije 
It looks like /data/js/* files can't be read. They should exist, so it's probably a lack of permissions.
Can you `chmod 444 data/js/*`?

**Comment by kije** [comment]
Doesn't help, still got the same error. As I said, it also happens when I'm calling ->minify() without prividing any JS files to the minifier, or when I do the following:

	$minifier = new Minify\JS();
	$minifier->add('alert("TEST");');
	$minifier->minify($_SERVER['DOCUMENT_ROOT'] . 'jsmin.js');

(I made sure, php could write to this location)

**Comment by matthiasmullie** [comment]
Odd; I still can't reproduce, even with the exact same snippet of code.

Judging from the usage of `$_SERVER`, you're probably running this from apache? Can you make sure that the apache user (not just PHP user) has access to read from the `data/js/` folder (where the .txt files used by minifier are located)?

**Comment by kije** [comment]
Found the error. I didn't know that I also had to copy <code>data/js/*</code> from the repository (I use minify witout composer, so I followed the instructions in https://github.com/matthiasmullie/minify/issues/48), and when you refered to <code>data/js/</code> above, I thought you meant my directory where I saved my JS files 
Sry fort that
