### ISSUE TITLE
JS Error after minfiying

### ISSUE THREAD

**Issue by GM-Alex** [matthiasmullie/minify#66]
The valid code

```js
$(coming.wrap).bind('onReset', function () {
	try {
		$(this).find('iframe').hide().attr('src', '//about:blank').end().empty();
	} catch (e) {}
});
```

becomes the following invalid code

```js
$(coming.wrap).bind('onReset', function () {
        try {
          $(this).find('iframe').hide().attr('src', '}catch(e){}});
```

**Comment by matthiasmullie** [comment]
Hi @GM-Alex 

I am unable to reproduce this issue with the piece of code you posted.
I've added it to the test suite (https://github.com/matthiasmullie/minify/commit/44cbb9c0f5a46a8e4740b7a449598e8c6ba5a607) and it seems to work fine.

Can you doublecheck if you still encounter this issue with minifier's current MASTER code?
If it still happens to you, the issue may be caused elsewhere in your source code, but only be visible in this small bit of code. So if you still encounter the problem, any chance you could post the entire file?

**Comment by GM-Alex** [comment]
@matthiasmullie Seems that the fix for the issue I reported early also fix this one. So I forgot to pull the latest changes. Sorry for that.

**Comment by matthiasmullie** [comment]
No problem, glad to hear it works now :)
