### ISSUE TITLE
media queries and conditional comments

### ISSUE THREAD

**Issue by christhomas** [matthiasmullie/minify#72]
something that I would like to see would be the support for inline media query attributes and conditional comments.

cause when i'm building the set of files to use, I'm on the server and I don't know what would happen when the information is used by the browser.

so when I build an object to handle this type of data myself, I added support for inline media queries and conditional comments, which basically wrote the appropriate HTML tags to where I wanted to output them.

is this already supported, or even a desirable feature in the code? I think it would help to simplify the management of these attributes greatly, what do you think?

**Comment by matthiasmullie** [comment]
Hi @christhomas 
I'm afraid it's not entirely clear to me what you would like to accomplish.
Can you perhaps give some code examples to help me understand?

**Comment by matthiasmullie** [comment]
Due to inactivity, I'll close this task for now. Please do reopen this task if you can further help me understand the ask! :)

**Comment by christhomas** [comment]
Hi, sorry matthias I didnt check this for a while.

I realise that probably I made a mistake when I was looking at this that in fact it just provides the minification system for the raw data, not any particular way to inject the html tags into the pages, which means I rethought my issue and realised that I would have to wrap up this object with another class which generates the specific tags to insert into the pages.

so the issue was a misunderstanding I think, I'll use your library to minify the resources, but I'll write another class around it which takes the output from the processing and generates the required tags

I hope I understood it correctly this time ;)

**Comment by matthiasmullie** [comment]
Aha, yes I now understand. You're correct: all this class does is minify CSS & JS. How you include those minified files into your project is up to you :)
