### ISSUE TITLE
Run Minify on a string instead of a file?

### ISSUE THREAD

**Issue by orrd** [matthiasmullie/minify#73]
There doesn't appear to be a way to just pass a string of Javascript or CSS to Minify and have it return the minified version.  That ability would make it more useful for more situations, especially as "middleware" in Laravel or other frameworks, or for incorporating into a caching system or existing build process.

Is there any reason that couldn't be added?  Should I start looking at the code and come up with a pull request for that?

**Comment by matthiasmullie** [comment]
Actually, you can pass either the path to a file, or the code directly as string. It will try to find the file, and if that failed, it'll consider it code.

Both of these will work:

```php
$minifier = new Minify\CSS('body { color: red; }');
echo $minifier->minify();
```
```php
$minifier = new Minify\CSS();
$minifier->add('body { color: green; }');
echo $minifier->minify();
```
And same for the JS minifier.

**Comment by matthiasmullie** [comment]
And I just noticed that it is not obvious from the README examples. While it's briefly mentioned (*"or even complete CSS/JS content"*), there is indeed no example.

Feel free to submit a PR and make it more obvious with an example :)

**Comment by orrd** [comment]
Aha!  Now that I look at it again, it is actually mentioned in the examples also ("or we can just add plain CSS").  I guess maybe we both overlooked that part when skimming over the README?

**Comment by matthiasmullie** [comment]
Yeah. I'll close it, it's in there :p
If you think it'd be useful to also have a code example where code is passed as string, feel free to PR.
