### ISSUE TITLE
Somethin wrong with "background-"

### ISSUE THREAD

**Issue by PekopT** [matthiasmullie/minify#74]
I don't know CSS well, so I can't say what is wrong exactly, but this peace of code is breaking all:

```
@media only screen and (-webkit-min-device-pixel-ratio: 1.5),
only screen and (min--moz-device-pixel-ratio: 1.5),
only screen and (min-device-pixel-ratio: 1.5) {

    #fancybox-loading,.fancybox-close,.fancybox-prev span,.fancybox-next span {
        background-image: url('/path/to/image.png');
        background-size: 44px 152px;
    }

    #fancybox-loading div {
        background-image: url('/path/to/image.gif');
        background-size: 24px 24px;
    }
}
```

Any thoughts?

**Comment by matthiasmullie** [comment]
Hi @PekopT 

I can not reproduce this problem. I've [added this to the test suite](https://github.com/matthiasmullie/minify/commit/a1e998819567c9569c39ad2fc98463430529beeb) but it seems to minify how I would expected it to.

Any chance you can post what the result looks like for you? And I assume this is not your entire CSS, so the error may be caused somewhere else but only become visible here. Any change you could post the rest of your CSS as well?

**Comment by PekopT** [comment]
Thanks for reply.
need some time to prepare test archive.

**Comment by matthiasmullie** [comment]
Due to inactivity, I'll close this task for now. Please do reopen this task if you can further help me figure out the problem! :)
