### ISSUE TITLE
Stripping the last ;?

### ISSUE THREAD

**Issue by w3l** [matthiasmullie/minify#75]
Not sure if this is a bug or by design but combining multiple minified js-files into one can cause:

"Uncaught SyntaxError: Unexpected token var"

I solved it by adding a semicolon in between the blocks of minified javascript code.

Just bringing it up, perhaps it's a good idea to keep the last semicolon in minified js just to keep it more compatible with other code?

**Comment by matthiasmullie** [comment]
Hi @w3l 

Any chance you minified the scripts one by one and combined them yourself?

Minify has built-in support for combining multiple files:

```php
$minifier = new Minify\JS();
$minifier->add($source1);
$minifier->add($source2);
$minifier->minify($target);
```

In the minified result, the last ; should be stripped, but the one in between both scripts should still be there.

**Comment by w3l** [comment]
Well, there is a big chance that I "minified the scripts one by one and combined them yourself". ;-)

I guess the point was that keeping the last ; in the output would create less hassle when copy/pasting or combining the minified file with other files. It feels like 1 character is a small price to pay to keep the output more compatible with other potential uses. But it's just a suggestion.
