### ISSUE TITLE
Where is Converter class?

### ISSUE THREAD

**Issue by ymakux** [matthiasmullie/minify#79]
There in CSS.php exists reference to path converter class, but I unable to find it in the source files. Got error "Class 'MatthiasMullie\PathConverter\Converter' not found in ...". How to fix it?

**Comment by nicolas-pecher** [comment]
You must install minify with composer to resolve the dependencies to 3rd party libraries: https://github.com/matthiasmullie/minify#installation

**Comment by ymakux** [comment]
Thank you. Converter is a separate project available at https://github.com/matthiasmullie/path-converter (for those who'll have the same trouble)
