### ISSUE TITLE
How can I integrate it in my website? 

### ISSUE THREAD

**Issue by Dakoom** [matthiasmullie/minify#80]
Hi there, I'd like to know how can I integrate this script in my website. I know there are some instructions... but I really don't understand them. :-p
Can please somebody tell me how to include this on a PHP webpage?

**Comment by matthiasmullie** [comment]
Hi @Dakoom,

Ideally, you would install it with [composer](https://getcomposer.org/).
You can just run this in console:
```sh
composer require matthiasmullie/minify
```

You could also just manually include the files, for which you can find instructions here: https://github.com/matthiasmullie/minify/issues/48

**Comment by Dakoom** [comment]
Thank you Matthias for your fast reply! Really appreciated! I had seen that discussion... but I really can't understand. Let's say I want to create mysite.com/minify/ not using Composer...
Basically I have to download the entire package from here and put it in the /minify/ folder and the create an index.php with this content:
<?php
require_once 'minify/Minify.php';
require_once 'minify/CSS.php';
require_once 'minify/JS.php';
require_once 'minify/Exception.php';
require_once 'minify/Converter.php';
use MatthiasMullie\Minify;
?>

? Is this the case or am I wrong?

**Comment by matthiasmullie** [comment]
Converter.php is not part of this project, but of [path-converter](https://github.com/matthiasmullie/path-converter)

So you have to download both projects & include their files:

```php
require_once $minifyPath . '/src/Minify.php';
require_once $minifyPath . '/src/CSS.php';
require_once $minifyPath . '/src/JS.php';
require_once $minifyPath . '/src/Exception.php';
require_once $converterPath . '/src/Converter.php';
```

**Comment by Dakoom** [comment]
Ok, excuse me for my questions (I know probably they could appear to be dumb questions, but I'm a pretty noob on these type of things). So, now I have this in my public_html

index.php
-/minify/
-/path-converter/

In index.php I have this code: 

<?php 

require_once $minifyPath . 'minify/src/Minify.php';
require_once $minifyPath . 'minify/src/CSS.php';
require_once $minifyPath . 'minify/src/JS.php';
require_once $minifyPath . 'minify/src/Exception.php';
require_once $converterPath . 'path-converter/src/Converter.php';

?>

But now when I go to that page I just can't see anything.

**Comment by matthiasmullie** [comment]
Try this:
```php
<?php
require_once __DIR__ . '/minify/src/Minify.php';
require_once __DIR__ . '/minify/src/CSS.php';
require_once __DIR__ . '/minify/src/JS.php';
require_once __DIR__ . '/minify/src/Exception.php';
require_once __DIR__ . '/path-converter/src/Converter.php';
```
I just put the variables $minifyPath & $converterPath there because I didn't know the exact path they would be ;)

**Comment by Dakoom** [comment]
Nothing. I get the same a blank page. 
Now:

index.php
-/minify/
-/path-converter/

In index.php I have *just* this code: 

<?php
require_once __DIR__ . '/minify/src/Minify.php';
require_once __DIR__ . '/minify/src/CSS.php';
require_once __DIR__ . '/minify/src/JS.php';
require_once __DIR__ . '/minify/src/Exception.php';
require_once __DIR__ . '/path-converter/src/Converter.php';

?>

I'm in localhost with MAMP.

**Comment by matthiasmullie** [comment]
The blank page is to be expected: all you do there is include the required files for minification. You don't yet do anything with the code.

I'm not sure exactly how you wish to use it, so here's some example code on how to use the minifier.
See [README.md](https://github.com/matthiasmullie/minify/blob/master/README.md) for more documentation.

```php
use MatthiasMullie\Minify;

$sourcePath = '/path/to/source/css/file.css';
$minifier = new Minify\CSS($sourcePath);

// we can even add another file, they'll then be
// joined in 1 output file
$sourcePath2 = '/path/to/second/source/css/file.css';
$minifier->add($sourcePath2);

// or we can just add plain CSS
$css = 'body { color: #000000; }';
$minifier->add($css);

// save minified file to disk
$minifiedPath = '/path/to/minified/css/file.css';
$minifier->minify($minifiedPath);

// or just output the content
echo $minifier->minify();
```

**Comment by Dakoom** [comment]
Basically I just want to have a page like this: http://www.minifier.org/
Can you please tell me the exact script you used there?

**Comment by matthiasmullie** [comment]
Well, you're on your own there :)
This minifier will just let you minify CSS or Javascript, but it's up to you to build something with it :p

**Comment by Dakoom** [comment]
I was hoping on some help from you! :-D
