### ISSUE TITLE
Error in array please fix

### ISSUE THREAD

**Issue by debashishkumar** [matthiasmullie/minify#81]
Gives error in mobile only
https://drive.google.com/file/d/0B8xKzYRoqp6oT3FkaWtrU3JGOFE/view
https://drive.google.com/file/d/0B8xKzYRoqp6oLVM4Vy1xOEFxNEU/view?usp=docslist_api
Please fix this soon

**Comment by armababy** [comment]
It's obvious that this is not product you are having problems with.

You should contact developer of wordpress plugin you are using https://github.com/wp-plugins/merge-minify-refresh
