### ISSUE TITLE
How can i use minify without composer?

### ISSUE THREAD

**Issue by dmitry-git** [matthiasmullie/minify#82]
I read this issue:
https://github.com/matthiasmullie/minify/issues/48

But i cant find this files:
require_once $path . '/minify/src/JS.php';
require_once $path . '/minify/src/Exception.php';
require '../system/path-converter/src/Converter.php';

This information is no longer relevant?

**Comment by matthiasmullie** [comment]
I've posted more detailed instructions here: https://github.com/matthiasmullie/minify/issues/83
