### ISSUE TITLE
How to use Minify without composer

### ISSUE THREAD

**Issue by matthiasmullie** [matthiasmullie/minify#83]
1. Clone this (minifier) repository: https://github.com/matthiasmullie/minify
2. Clone path-converter repository: https://github.com/matthiasmullie/path-converter
3. Include all files from both projects.
Assuming you cloned both projects to `/path/to/libraries/`, that would look like this:
```php
// make sure to update the path to where you cloned the projects to!
$path = '/path/to/libraries';
require_once $path . '/minify/src/Minify.php';
require_once $path . '/minify/src/CSS.php';
require_once $path . '/minify/src/JS.php';
require_once $path . '/minify/src/Exception.php';
require_once $path . '/path-converter/src/Converter.php';
```
4. Use minifier! E.g.:
```php
$minifier = new Minify\CSS('body { color: red; }');
echo $minifier->minify();
```

**Comment by dmitry-git** [comment]
Thanks It works.
But how to use short links here?
For example: domain.com/min/?f=... in link tag?

**Comment by PaoloFalomo** [comment]
:warning: over here. If you use clone it will add /tests/ folders too. And it's not necessary to upload them. Could you please give us a non-composer-needed blob?

**Comment by tjespe** [comment]
Is the path-converter library really necessary? What does it do?

**Comment by matthiasmullie** [comment]
Yes it is. It will convert relative paths in your CSS files if the location of the minified files is different from the source file. It also fixes relative paths inside `@import`ed files, when their content is included in the main minified code.

**Comment by jfoclpf** [comment]
Do you need to include the CSS.php if you just want to minify JS? Is there any means to make it lighter for some purposes?

**Comment by matthiasmullie** [comment]
If you're only minifying JS, you don't need to include CSS.php. And the other way around.
And if really needed: as long as the code doesn't have to thrown any exceptions, you could also not include those exception files.

**Comment by AubinMahe** [comment]
I have this error, why?

    Call to undefined function MatthiasMullie\PathConverter\mb_substr()

**Comment by reardestani** [comment]
we can also use this site: https://php-download.com/package/matthiasmullie/minify

Then we can simply require one file like: `require_once $path . '/minify/index.php';`

**Comment by liquorburn** [comment]
Hi there,
I'm using Minify without composer and I'd like to generate one minified CSS file from five source files, like this:
`$sourcePath = '/src/css/main.css';
$minifierCSS = new Minify\CSS($sourcePath);
$sourceCSS = array(
	'css_source2.css',
	'css_source3.css',
	'css_source4.css',
	'css_source5.css'
);
foreach ($sourceCSS as $css) $minifierCSS->add($css);
$minifiedPath = BASEDIR.'/css/minified.css';
$minifierCSS->minify($minifiedPath);`

The file minified.css is created but it only contains the paths of the source CSS files, do you know why?

**Comment by nileio** [comment]
@matthiasmullie thanks for the library .. if i only use it to minify CSS, do I need to include data/js directory?
