### ISSUE TITLE
PHP operator is incorrect in JS.php file line 225?

### ISSUE THREAD

**Issue by dmitry-git** [matthiasmullie/minify#84]
Use the point symbol (not `+`) to concatenate strings in PHP.
```PHP
$operators .= $this->getKeywordsForRegex($this->keywordsReserved, '/');
```

**Comment by matthiasmullie** [comment]
getKeywordsForRegex() doesn't return a string, but an array (of strings). They're being merged into the already existing array $operators, so the + is valid here.
