### ISSUE TITLE
UglifyJS test suite

### ISSUE THREAD

**Issue by szepeviktor** [matthiasmullie/minify#88]
Good morning!

Please consider adding UglifyJS' test suite.
Your project seems more tempting because of CSS minification support
but https://github.com/tchwork/jsqueeze passes UglifyJS' test suite.

**Comment by matthiasmullie** [comment]
I like the idea, but I'm not going to do this.

UglifyJS's test suite is geared towards their own implementations and issues that were specific to how their minification works. A lot of them are irrelevant for this minifier (and vice versa).
It's not that I don't believe UglifyJS does a decent enough job (I would actually recomment it over my minifier if you're able to run it; when you can integrate that build step into your PHP app), I just don't think their test suite is relevant here too.

There's also implementation differences between UglifyJS & this minifier. E.g. judging from https://github.com/mishoo/UglifyJS2/blob/master/test/compress/issue-208.js, it looks like UglifyJS doesn't minify `false` into `!1`. There's also several things UglifyJS does do and this minifier doesn't.
