### ISSUE TITLE
Problem after minifying facebook sdk

### ISSUE THREAD

**Issue by Fluoo** [matthiasmullie/minify#89]
Hello,

I use your to minify some personnal js files and some external js file.
my problem is that the minification of the facebook sdk break the file.

The file I try to minify :
https://connect.facebook.net/fr_FR/sdk.js

Regards.

**Comment by matthiasmullie** [comment]
Hi @Fluoo,

This should be fixed in da03f6d13c3d4e6fde76eb4eebbcc44508f38b6e. I'll push a new release soon!

Also, I noticed that sdk.js seems to be minified already. You'll squeeze out a couple more bytes by minifying it again, but it won't be much :)
