### ISSUE TITLE
Test Results

### ISSUE THREAD

**Issue by GinoPane** [matthiasmullie/minify#93]
Hello!
I've just run all available tests for the master branch of minify and got such results:

FAILURES!
Tests: 167, Assertions: 174, Failures: 29.

Is it ok? 
I use PHP 7.0.1.

**Comment by matthiasmullie** [comment]
Hi @GinoPane 

The tests are supposed to pass. I just ran them again on Travis CI where they seemed to pass just fine (against PHP 7.0.2 though): https://travis-ci.org/matthiasmullie/minify/jobs/104719208

Can you let me know which tests failed & how?

**Comment by GinoPane** [comment]
Yeah, sure. But a little bit later. 
I'll update to 7.0.2 too and run them again.

**Comment by matthiasmullie** [comment]
No need to update to 7.0.2. I don't think the exact PHP version is relevant (it should work from 5.3 to 7.whatever).

**Comment by GinoPane** [comment]
I've updated to 7.0.2 for consistency:)

Here's xml report of testing results: https://yadi.sk/d/yWkTyP0ToJLpp . I ran them on Windows, PHP 7.0.2, PHPUnit 5.1.7.

**Comment by GinoPane** [comment]
Failures start on importing symbolic links. It just reads content of the file with relative path and puts it in resulting css.

**Comment by matthiasmullie** [comment]
@GinoPane I'm think you're right - the symbolic links tests must be why they're failing on Windows. I'll take a more detailed look, but it may take me some time before I get around to setting up a proper Windows environment to look into this.

**Comment by GinoPane** [comment]
@matthiasmullie I'm afraid, I have the same issues on Linux environment also. Not native though, but virtual. Here's the screenshot: http://prntscr.com/a08n8b (first run was broken, cause I've already started to debug and fix some parts, but then I've switched to master again). 

Is there any possibility that code in master branch differs from that where all tests pass? And I am confused, why the directory directory ```css/sample/convert_ralative_path/target``` was removed (http://prntscr.com/a08uq4), cause I had to create it manually in order to simply run tests without exceptions (http://prntscr.com/a08qlj).

I have started to investigate code and have already fixed 4 failures, but I am not sure that this is not useless work. Maybe I have something more missed in the codebase and that is why I can not get all tests passing. Or maybe I should build anything before tests? I simply run phpunit. Only ```composer install``` was run before.

**Comment by GinoPane** [comment]
@matthiasmullie Checked again on native Linux - works fine.

**Comment by GinoPane** [comment]
@matthiasmullie I've investigated the problem for CSS tests and now they work for me (I'll submit a pull request later). But it fixes only 8 failures, others (21) are with JSTest and I haven't investigated them yet.

**Comment by GinoPane** [comment]
Everything's fixed now. Please have a look at my pull request: https://github.com/matthiasmullie/minify/pull/95

**Comment by matthiasmullie** [comment]
Merged your PR, thanks!
