### ISSUE TITLE
// in string is treated as comment (fancybox 2.1.5)

### ISSUE THREAD

**Issue by demacrocom** [matthiasmullie/minify#97]
Hello,

I just found that the JS minifier will treat some strings as comments, even though they are surrounded by ' characters. To be precise: In fancybox 2.1.5 on line 998 there is this code
    ...attr('src', '//about:blank').end().empty();
which is minified to
    ...attr('src', '
and obviously is not, what one would expect.

As far as I understood your code, these things should be no problem, because prior to removing comments, you pull out all strings, which should include '//about:blank', but for whatever reason it seems to choke on it in this case.

I'd really appreciate if you could have a look at this. Thanks a lot in advance!
Dominik

**Comment by GinoPane** [comment]
Do you use the latest version?

Just tested on this file: https://github.com/fancyapps/fancyBox/blob/master/source/jquery.fancybox.js.

Lines 1001-1005: 
"$(coming.wrap).bind('onReset', function () {
				try {
					$(this).find('iframe').hide().attr('src', '//about:blank').end().empty();
				} catch (e) {}
			});"

were minified to:

"$(coming.wrap).bind('onReset',function(){try{$(this).find('iframe').hide().attr('src','//about:blank').end().empty()}catch(e){}})".

The same result for the whole file. Screenshot: http://prntscr.com/a45iko.

**Comment by demacrocom** [comment]
Yes, latest version (at least latest release, 1.3.32). Just tested the file you referenced, but minify still behaves this oddly. I don't really see a reason for this, because your code does everything to prevent this behaviour. Will have to investigate further

Could you test the attached file against release 1.3.32, please? Perhaps there's something wrong in the way I pass the file to minify...
[fancybox-2.1.5-cdn.js.zip](https://github.com/matthiasmullie/minify/files/134528/fancybox-2.1.5-cdn.js.zip)

**Comment by matthiasmullie** [comment]
I haven't yet looked into it, but since @GinoPane reports it actually works for him, it may not be an issue with the code but a difference in setup.

Can you try increasing your `pcre.backtrack_limit` to something higher?
See http://php.net/manual/en/pcre.configuration.php

**Comment by demacrocom** [comment]
Set backtrack_limit to 10.000.000, but that didn't change anything :(

Why I asked for a test to my file: prior to minify I add two small comments to the top and bottom of the file. Though I can't see anything wrong there, that **could** be part of the problem.

**Comment by matthiasmullie** [comment]
I just tried minifying the file you linked and this is the result: http://pastebin.com/Lcx1Jjht
It looks to have minified just fine:
```js
... find('iframe').hide().attr('src','//about:blank').end().empty()}catch(e ...
```

Do you still happen to have the original source you tried to minify (including the comments)? Any chance you could upload that somewhere?

**Comment by demacrocom** [comment]
The file I added to my comment was the one with comments. That is what I pass to minify.

This is really strange...
I'll dig into this a little bit deeper. At least I know it must be something on my end and can't be the file or the minify code.

Thanks a lot everyone!

**Comment by demacrocom** [comment]
Got it! I fiddled in my code and after clearing the cache it worked. Unfortunately I don't really know, which exact change fixed this behaviour, but it works now.

Thanks again for your support! That was very helpful for eliminating possible causes!

**Comment by matthiasmullie** [comment]
Glad to hear you got it to work eventually! :)
