### ISSUE TITLE
Issue with "0" replacement with "object"

### ISSUE THREAD

**Issue by titovmaxim** [matthiasmullie/minify#99]
Our JS code stop work after minification. The examination has showed that it is jQuery v1.12.1 (minified version) which was broken. Please find below several examples what was wrong in the minified version (original / minified)

```
{var l,o,q,r=0,s="0",t=f&&[]
{var l,o,q,r=0,s="object",t=f&&[]

l.ownFirst="0"===L,l.inlineBlockNeedsLayout=!1
l.ownFirst="object"===L,l.inlineBlockNeedsLayout=!1

$a={letterSpacing:"0",
$a={letterSpacing:"object",
```

Apparently the problem is with replacement of "0" to "object", which is not correct.

**Comment by titovmaxim** [comment]
I think the problem could be with "lovely" PHP string "0" handling in empty() function. Probably it is in  Minify.php line 321:
```
if (!$match[2]) {
```

Which I guess should be:
```
if ($match[2] === '') {
```

**Comment by matthiasmullie** [comment]
You were absolutely correct about what causes the problem.
Any chance you could try current master? If the fix works for you, I'll push a new release.

**Comment by titovmaxim** [comment]
I think it should be without not (!) operator. The condition should match is if string is empty, right?

**Comment by matthiasmullie** [comment]
Oomph, good catch! That was sloppy :)
Fixed.

**Comment by titovmaxim** [comment]
This version works well :)

**Comment by jeroendesloovere** [comment]
:+1:
